In [2]:
import pandas as pd

## replace "." with "-" from R output rownames

In [29]:
#filename = "../bindSC_labelTransfer.tsv"
filename = "../bindSC_umap3D_coembedding.tsv"
#filename = "../bindSC_cell_annotation_coembedding.tsv"

In [30]:
df = pd.read_csv(filename, sep='\t',  index_col=0)
df

                        UMAP1     UMAP2     UMAP3
aadomelj.1           9.085867 -1.162853 -1.592060
aadooijh.1          10.135071 -2.579623 -1.324015
aadpffob.1          10.501189 -2.970432  0.092537
aadpkdac.1           7.534844 -2.827466 -0.417515
aadplnnc.1           8.250260 -0.300717 -0.747280
...                       ...       ...       ...
TTTGTTGGTTCGATTG-1   9.671985 -0.480696 -0.020481
TTTGTTGTCAACTGAC-1   7.476856 -3.276488  0.292763
TTTGTTGTCAATCGGT-1  10.402995 -2.245508 -0.616560
TTTGTTGTCCGCTAGG-1   9.054682 -3.485623  0.936251
TTTGTTGTCCGTTGAA-1   9.312481 -1.233366  4.564732

[36003 rows x 3 columns]

In [31]:
df.index  = df.index.str.replace('.', '-')
df

                        UMAP1     UMAP2     UMAP3
aadomelj-1           9.085867 -1.162853 -1.592060
aadooijh-1          10.135071 -2.579623 -1.324015
aadpffob-1          10.501189 -2.970432  0.092537
aadpkdac-1           7.534844 -2.827466 -0.417515
aadplnnc-1           8.250260 -0.300717 -0.747280
...                       ...       ...       ...
TTTGTTGGTTCGATTG-1   9.671985 -0.480696 -0.020481
TTTGTTGTCAACTGAC-1   7.476856 -3.276488  0.292763
TTTGTTGTCAATCGGT-1  10.402995 -2.245508 -0.616560
TTTGTTGTCCGCTAGG-1   9.054682 -3.485623  0.936251
TTTGTTGTCCGTTGAA-1   9.312481 -1.233366  4.564732

[36003 rows x 3 columns]

In [32]:
df.to_csv(filename, sep="\t")