In [3]:
import pandas as pd
import numpy as np
import os

## set up

In [2]:
info_file = "datasets.info.2025-11-18.txt"
metadata_file ="combined_UCE_5neuro/obs_anno.tsv" # expect there is a column called dataset_id, first column
#out_file ="combined_UCE_5neuro/obs_anno.tsv"

## data info from file -> data (df)

In [4]:
info_df = pd.read_csv(info_file, sep="\t")
info_df = info_df.set_index("dataset_id")
info_df

,dataset_total_cell_count,collection_name,dataset_title,collection_doi_label
dataset_id,,,,
149b2c3f-ee11-47a7-984b-923570280bd7,301,HVS: Human variation study,SstChodl - neocortex: Human variation study (HVS),Johansen et al. (2023) Science
5e7fff82-b8eb-4220-bf65-c6feb6765ea1,563,HVS: Human variation study,L5ET - neocortex: Human variation study (HVS),Johansen et al. (2023) Science
4859642c-d155-437b-adf5-83ca6c1bef67,582,HVS: Human variation study,Endo - neocortex: Human variation study (HVS),Johansen et al. (2023) Science
f9cfac8d-bff6-47a2-a1f6-503827d375f5,637,HVS: Human variation study,VLMC - neocortex: Human variation study (HVS),Johansen et al. (2023) Science
a65bcc2d-4243-44c1-a262-ab7dcddfcf86,810,Longitudinal profiling of respiratory and syst...,74 years old female - Airway Wash (7 days post...,Szabo et al. (2021) Immunity
...,...,...,...,...
9dbab10c-118d-496b-966a-67f1763a6b7d,1462702,COVID-19 immune features revealed by a large-s...,Large-scale single-cell analysis reveals criti...,Ren et al. (2021) Cell
13149914-ea03-4f01-8bf6-b793b667127b,1665937,Comprehensive cell atlas of the first-trimeste...,All,Braun et al. (2023) Science
9f222629-9e39-47d0-b83f-e08d610c7479,2282447,The integrated Human Lung Cell Atlas,An integrated cell atlas of the human lung in ...,Sikkema et al. (2023) Nat Med
8e10f1c4-8e98-41e5-b65f-8cd89a887122,2480956,Human Brain Cell Atlas v1.0,All neurons,Siletti et al. (2023) Science
f7c1c579-2dc0-47e2-ba19-8165c5a0e353,4062980,A human cell atlas of fetal gene expression,Survey of human embryonic development,Cao et al. (2020) Science

In [5]:
dataset_info = info_df.to_dict(orient="index")
dataset_info

{'149b2c3f-ee11-47a7-984b-923570280bd7': {'dataset_total_cell_count': 301,
  'collection_name': 'HVS: Human variation study',
  'dataset_title': 'SstChodl - neocortex: Human variation study (HVS)',
  'collection_doi_label': 'Johansen et al. (2023) Science'},
 '5e7fff82-b8eb-4220-bf65-c6feb6765ea1': {'dataset_total_cell_count': 563,
  'collection_name': 'HVS: Human variation study',
  'dataset_title': 'L5ET - neocortex: Human variation study (HVS)',
  'collection_doi_label': 'Johansen et al. (2023) Science'},
 '4859642c-d155-437b-adf5-83ca6c1bef67': {'dataset_total_cell_count': 582,
  'collection_name': 'HVS: Human variation study',
  'dataset_title': 'Endo - neocortex: Human variation study (HVS)',
  'collection_doi_label': 'Johansen et al. (2023) Science'},
 'f9cfac8d-bff6-47a2-a1f6-503827d375f5': {'dataset_total_cell_count': 637,
  'collection_name': 'HVS: Human variation study',
  'dataset_title': 'VLMC - neocortex: Human variation study (HVS)',
  'collection_doi_label': 'Johansen et al. (2023) Science'},
 'a65bcc2d-4243-44c1-a262-ab7dcddfcf86': {'dataset_total_cell_count': 810,
  'collection_name': 'Longitudinal profiling of respiratory and systemic immune responses reveals myeloid cell-driven lung inflammation in severe COVID-19',
  'dataset_title': '74 years old female - Airway Wash (7 days post-intubation)',
  'collection_doi_label': 'Szabo et al. (2021) Immunity'},
 '0c9a8cfb-6649-4d52-b418-6d8e56bd7afe': {'dataset_total_cell_count': 1011,
  'collection_name': 'Single-cell and spatial transcriptomics characterisation of the immunological landscape in the healthy and PSC human liver',
  'dataset_title': 'Cholangiocytes from human healthy donor liver samples',
  'collection_doi_label': 'Andrews et al. (2024) Journal of Hepatology'},
 'b25f3834-69b3-4d87-a272-3938432d1f30': {'dataset_total_cell_count': 1074,
  'collection_name': 'Longitudinal profiling of respiratory and systemic immune responses reveals myeloid cell-driven lung inflammation in severe COVID-19',
  'dataset_title': '82 years old female - Airway Wash (1 day post-intubation)',
  'collection_doi_label': 'Szabo et al. (2021) Immunity'},
 '4993d61c-1d04-4630-9c61-8d9431f39adc': {'dataset_total_cell_count': 1250,
  'collection_name': 'Single-cell and spatial transcriptomics characterisation of the immunological landscape in the healthy and PSC human liver',
  'dataset_title': 'B cells from human healthy donor liver samples',
  'collection_doi_label': 'Andrews et al. (2024) Journal of Hepatology'},
 'a5d95a42-0137-496f-8a60-101e17f263c8': {'dataset_total_cell_count': 1324,
  'collection_name': 'Single-cell Atlas of common variable immunodeficiency shows germinal center-associated epigenetic dysregulation in B-cell responses',
  'dataset_title': 'Steady-state B cells - scRNA-seq',
  'collection_doi_label': 'Rodríguez-Ubreva et al. (2022) Nat Commun'},
 'eec804b9-2ae5-44f0-a1b5-d721e21257de': {'dataset_total_cell_count': 1324,
  'collection_name': 'Longitudinal profiling of respiratory and systemic immune responses reveals myeloid cell-driven lung inflammation in severe COVID-19',
  'dataset_title': '74 years old female - Airway Wash (5 days post-intubation)',
  'collection_doi_label': 'Szabo et al. (2021) Immunity'},
 'e347396c-a7ff-4691-9f7a-99a43555ca18': {'dataset_total_cell_count': 1417,
  'collection_name': 'Single-cell and spatial transcriptomics characterisation of the immunological landscape in the healthy and PSC human liver',
  'dataset_title': 'Stellate cells from human healthy donor liver samples',
  'collection_doi_label': 'Andrews et al. (2024) Journal of Hepatology'},
 '78f40dd6-ed22-470d-8547-6fb5746c25da': {'dataset_total_cell_count': 1465,
  'collection_name': 'HVS: Human variation study',
  'dataset_title': 'Pax6 - neocortex: Human variation study (HVS)',
  'collection_doi_label': 'Johansen et al. (2023) Science'},
 '30f5e171-83d7-4fc0-bf75-384f122346b3': {'dataset_total_cell_count': 1790,
  'collection_name': 'Cell-type specific analysis of physiological action of estrogen inmouse oviducts',
  'dataset_title': 'scRNA-seq data of human fallopian tube',
  'collection_doi_label': 'McGlade et al. (2021) FASEB j.'},
 'd973ea15-3722-4bc8-a0e8-1d956d26e203': {'dataset_total_cell_count': 1837,
  'collection_name': 'Single-nucleus transcriptomic analysis of human dorsal root ganglion neurons.',
  'dataset_title': 'Single-nucleus transcriptomic analysis of human dorsal root ganglion neurons',
  'collection_doi_label': 'Nguyen et al. (2021) eLife'},
 '6929d6d1-6f81-44d7-bd35-5a580259af81': {'dataset_total_cell_count': 1875,
  'collection_name': 'HVS: Human variation study',
  'dataset_title': 'Chandelier - neocortex: Human variation study (HVS)',
  'collection_doi_label': 'Johansen et al. (2023) Science'},
 'f3ee7613-b27f-4deb-a5aa-1d4f9a2db963': {'dataset_total_cell_count': 1971,
  'collection_name': 'High-resolution single-cell transcriptomic survey of cardiomyocytes from patients with hypertrophic cardiomyopathy',
  'dataset_title': "dataset of 'High-resolution single-cell transcriptomic survey of cardiomyocytes from patients with hypertrophic cardiomyopathy'",
  'collection_doi_label': 'Lu et al. (2024) Cell Proliferation'},
 '731e6380-879f-4b0b-9a1f-2150208852ef': {'dataset_total_cell_count': 2065,
  'collection_name': 'Longitudinal profiling of respiratory and systemic immune responses reveals myeloid cell-driven lung inflammation in severe COVID-19',
  'dataset_title': '74 years old female - Airway Wash (8 days post-intubation)',
  'collection_doi_label': 'Szabo et al. (2021) Immunity'},
 'd2bc2703-a9b5-4949-b85d-61da7b9961b1': {'dataset_total_cell_count': 2075,
  'collection_name': 'Smoking modulates different secretory subpopulations expressing SARS-CoV-2 entry genes in the nasal and bronchial airways',
  'dataset_title': 'Bronchial scRNA-Seq Dataset',
  'collection_doi_label': 'Xu et al. (2022) Sci Rep'},
 '601c7454-17ff-432c-8e0d-902bfddb8013': {'dataset_total_cell_count': 2094,
  'collection_name': 'Exploring the Utility of snRNA-seq in Profiling Human Bladder Tissue: A Comprehensive Comparison with scRNA-seq',
  'dataset_title': 'Adult bladder immune subset',
  'collection_doi_label': 'Santo et al. (2025) iScience'},
 'b07e5164-baf6-43d2-bdba-5a249d0da879': {'dataset_total_cell_count': 2126,
  'collection_name': 'Muraro Pancreas',
  'dataset_title': 'A Single-Cell Transcriptome Atlas of the Human Pancreas',
  'collection_doi_label': 'Muraro et al. (2016) Cell Systems'},
 'e5f5d954-cf0e-4bd8-9346-8d1ddf15a08b': {'dataset_total_cell_count': 2487,
  'collection_name': 'Longitudinal profiling of respiratory and systemic immune responses reveals myeloid cell-driven lung inflammation in severe COVID-19',
  'dataset_title': '49 years old male - Airway Wash (3 days post-intubation)',
  'collection_doi_label': 'Szabo et al. (2021) Immunity'},
 '7d98cc44-b090-4dc8-804f-2750c84fe9d7': {'dataset_total_cell_count': 2489,
  'collection_name': 'Longitudinal profiling of respiratory and systemic immune responses reveals myeloid cell-driven lung inflammation in severe COVID-19',
  'dataset_title': '49 years old male - Airway Wash (1 day post-intubation)',
  'collection_doi_label': 'Szabo et al. (2021) Immunity'},
 '66d15835-5dc8-4e96-b0eb-f48971cb65e8': {'dataset_total_cell_count': 2544,
  'collection_name': 'Single-Cell Analysis of Human Pancreas Reveals Transcriptional Signatures of Aging and Somatic Mutation Patterns',
  'dataset_title': 'Single cell transcriptome analysis of human pancreas reveals transcriptional signatures of aging and somatic mutation patterns',
  'collection_doi_label': 'Enge et al. (2017) Cell'},
 '4c6f9f26-5470-455b-8933-c408232fbf56': {'dataset_total_cell_count': 2576,
  'collection_name': 'Single-cell analyses of renal cell cancers reveal insights into tumor microenvironment, cell of origin, and therapy response',
  'dataset_title': 'chRCC - Single-cell analyses of renal cell cancers reveal insights into tumor microenvironment, cell of origin, and therapy response',
  'collection_doi_label': 'Zhang et al. (2021) Proc. Natl. Acad. Sci. U.S.A.'},
 '62de80d7-e6c4-4ff0-ad4c-d3d36f57cb93': {'dataset_total_cell_count': 2598,
  'collection_name': 'Longitudinal profiling of respiratory and systemic immune responses reveals myeloid cell-driven lung inflammation in severe COVID-19',
  'dataset_title': '66 years old female - Airway Wash (4 days post-intubation)',
  'collection_doi_label': 'Szabo et al. (2021) Immunity'},
 'ce009dc1-ac57-4386-b72f-5c575701c253': {'dataset_total_cell_count': 2834,
  'collection_name': 'Longitudinal profiling of respiratory and systemic immune responses reveals myeloid cell-driven lung inflammation in severe COVID-19',
  'dataset_title': '74 years old female - Airway Wash (6 days post-intubation)',
  'collection_doi_label': 'Szabo et al. (2021) Immunity'},
 '2f6a20f1-173d-4b8d-860b-c47ffea120fa': {'dataset_total_cell_count': 2868,
  'collection_name': 'Cell Atlas of The Human Fovea and Peripheral Retina',
  'dataset_title': 'Horizontal cells of the human fovea and peripheral retina',
  'collection_doi_label': 'Yan et al. (2020) Sci Rep'},
 'dbf0bd35-87f8-4b25-bc90-a3c54f379907': {'dataset_total_cell_count': 3434,
  'collection_name': 'Longitudinal profiling of respiratory and systemic immune responses reveals myeloid cell-driven lung inflammation in severe COVID-19',
  'dataset_title': '66 years old female - Airway Wash (3 days post-intubation)',
  'collection_doi_label': 'Szabo et al. (2021) Immunity'},
 '774c18c5-efa1-4dc5-9e5e-2c824bab2e34': {'dataset_total_cell_count': 3589,
  'collection_name': 'Single-Cell RNAseq analysis of diffuse neoplastic infiltrating cells at the migrating front of human glioblastoma',
  'dataset_title': 'Infiltrating Neoplastic Cells Human Glioblastoma',
  'collection_doi_label': 'Darmanis et al. (2017) Cell Reports'},
 '01c93cf6-b695-4e30-a26e-121ae8b16a9e': {'dataset_total_cell_count': 3726,
  'collection_name': 'Longitudinal profiling of respiratory and systemic immune responses reveals myeloid cell-driven lung inflammation in severe COVID-19',
  'dataset_title': '66 years old female - Fresh PBMCs (7 days post-intubation)',
  'collection_doi_label': 'Szabo et al. (2021) Immunity'},
 '80d7111d-f9fe-49fd-871e-6e618312c341': {'dataset_total_cell_count': 3797,
  'collection_name': 'Single-cell transcriptome analysis reveals differential nutrient absorption functions in human intestine',
  'dataset_title': 'Rectum',
  'collection_doi_label': 'Wang et al. (2020) Journal of Experimental Medicine'},
 'b6e502d7-0d07-408e-a291-91b63af0a40a': {'dataset_total_cell_count': 3934,
  'collection_name': 'HVS: Human variation study',
  'dataset_title': 'MicroPVM - neocortex: Human variation study (HVS)',
  'collection_doi_label': 'Johansen et al. (2023) Science'},
 '390b376d-8857-4b4b-991f-0d7326938172': {'dataset_total_cell_count': 4112,
  'collection_name': 'HVS: Human variation study',
  'dataset_title': 'Sncg - neocortex: Human variation study (HVS)',
  'collection_doi_label': 'Johansen et al. (2023) Science'},
 '51f476f7-b24d-42f3-8871-7dab3fa35e96': {'dataset_total_cell_count': 4147,
  'collection_name': 'Longitudinal profiling of respiratory and systemic immune responses reveals myeloid cell-driven lung inflammation in severe COVID-19',
  'dataset_title': '74 years old female - Airway Wash (4 days post-intubation)',
  'collection_doi_label': 'Szabo et al. (2021) Immunity'},
 '8a554710-08bc-4005-87cd-da9675bdc2e7': {'dataset_total_cell_count': 4232,
  'collection_name': 'Longitudinal profiling of respiratory and systemic immune responses reveals myeloid cell-driven lung inflammation in severe COVID-19',
  'dataset_title': '82 years old female - Fresh PBMCs (1 day post-intubation)',
  'collection_doi_label': 'Szabo et al. (2021) Immunity'},
 '4e74d843-8d7a-497a-918a-f079ef141b6d': {'dataset_total_cell_count': 4329,
  'collection_name': 'Single-cell transcriptome analysis reveals differential nutrient absorption functions in human intestine',
  'dataset_title': 'Colon',
  'collection_doi_label': 'Wang et al. (2020) Journal of Experimental Medicine'},
 'af8b241a-c72c-4470-b1a4-80e7336c6ab6': {'dataset_total_cell_count': 4335,
  'collection_name': 'Single-cell transcriptomics of the human retinal pigment epithelium and choroid in health and macular degeneration',
  'dataset_title': 'Retina',
  'collection_doi_label': 'Voigt et al. (2019) Proc. Natl. Acad. Sci. U.S.A.'},
 'cfa3c355-ee77-4fc8-9a00-78e61d23024c': {'dataset_total_cell_count': 4355,
  'collection_name': 'A single-cell transcriptional roadmap of the mouse and human lymph node lymphatic vasculature',
  'dataset_title': 'A Single-Cell Transcriptional Roadmap of the Mouse and Human Lymph Node Lymphatic Vasculature - human',
  'collection_doi_label': 'Xiang et al. (2020) Front. Cardiovasc. Med.'},
 '73b7d0aa-035f-4a15-9f1d-f56b70204591': {'dataset_total_cell_count': 4594,
  'collection_name': 'Longitudinal profiling of respiratory and systemic immune responses reveals myeloid cell-driven lung inflammation in severe COVID-19',
  'dataset_title': '66 years old female - Airway Wash (7 days post-intubation)',
  'collection_doi_label': 'Szabo et al. (2021) Immunity'},
 'c874f155-9bf9-4928-b821-f52c876b3e48': {'dataset_total_cell_count': 4603,
  'collection_name': 'Longitudinal profiling of respiratory and systemic immune responses reveals myeloid cell-driven lung inflammation in severe COVID-19',
  'dataset_title': '49 years old male - Fresh PBMCs (1 day post-intubation)',
  'collection_doi_label': 'Szabo et al. (2021) Immunity'},
 'ea01c125-67a7-4bd3-a8b0-e1b53a011b7e': {'dataset_total_cell_count': 4636,
  'collection_name': 'Single cell derived mRNA signals across human kidney tumors',
  'dataset_title': 'wilms',
  'collection_doi_label': 'Young et al. (2021) Nat Commun'},
 '2f7230e7-4706-4924-b571-473fc1e52c30': {'dataset_total_cell_count': 4651,
  'collection_name': 'Longitudinal profiling of respiratory and systemic immune responses reveals myeloid cell-driven lung inflammation in severe COVID-19',
  'dataset_title': '74 years old female - Airway Wash (1 day post-intubation)',
  'collection_doi_label': 'Szabo et al. (2021) Immunity'},
 'e2a325e2-5633-4950-ae46-ebff70979e3b': {'dataset_total_cell_count': 4683,
  'collection_name': 'HVS: Human variation study',
  'dataset_title': 'Lamp5Lhx6 - neocortex: Human variation study (HVS)',
  'collection_doi_label': 'Johansen et al. (2023) Science'},
 '470565f2-5afc-456a-b617-18e4496c04fd': {'dataset_total_cell_count': 4714,
  'collection_name': 'Human Brain Cell Atlas v1.0',
  'dataset_title': 'Dissection: Midbrain (RN) - Red Nucleus - RN',
  'collection_doi_label': 'Siletti et al. (2023) Science'},
 '50eb1e23-b8d4-4f76-a184-44e5541fa05a': {'dataset_total_cell_count': 4755,
  'collection_name': 'Longitudinal profiling of respiratory and systemic immune responses reveals myeloid cell-driven lung inflammation in severe COVID-19',
  'dataset_title': '74 years old female - Fresh PBMCs (8 days post-intubation)',
  'collection_doi_label': 'Szabo et al. (2021) Immunity'},
 'ea786a06-5855-48b7-80d7-0313a21a2044': {'dataset_total_cell_count': 4792,
  'collection_name': 'Longitudinal profiling of respiratory and systemic immune responses reveals myeloid cell-driven lung inflammation in severe COVID-19',
  'dataset_title': '66 years old female - Fresh PBMCs (3 days post-intubation)',
  'collection_doi_label': 'Szabo et al. (2021) Immunity'},
 '79ef1959-a6b4-4cac-82ca-30feaec48df1': {'dataset_total_cell_count': 4846,
  'collection_name': 'Longitudinal profiling of respiratory and systemic immune responses reveals myeloid cell-driven lung inflammation in severe COVID-19',
  'dataset_title': '74 years old female - Fresh PBMCs (7 days post-intubation)',
  'collection_doi_label': 'Szabo et al. (2021) Immunity'},
 'cab0bc48-744c-461b-aaf4-7bf2cb7af00d': {'dataset_total_cell_count': 5080,
  'collection_name': 'Longitudinal profiling of respiratory and systemic immune responses reveals myeloid cell-driven lung inflammation in severe COVID-19',
  'dataset_title': '74 years old female - Fresh PBMCs (4 days post-intubation)',
  'collection_doi_label': 'Szabo et al. (2021) Immunity'},
 'ee195b7d-184d-4dfa-9b1c-51a7e601ac11': {'dataset_total_cell_count': 5200,
  'collection_name': 'Charting human development using a multi-endodermal organ atlas and organoid models',
  'dataset_title': 'Adult duodenum',
  'collection_doi_label': 'Yu et al. (2021) Cell'},
 '0087cde2-967d-4f7c-8e6e-40e4c9ad1891': {'dataset_total_cell_count': 5399,
  'collection_name': 'HVS: Human variation study',
  'dataset_title': 'L6ITCar3 - neocortex: Human variation study (HVS)',
  'collection_doi_label': 'Johansen et al. (2023) Science'},
 '810ac45f-8969-4698-b42c-652f802f75c2': {'dataset_total_cell_count': 5467,
  'collection_name': 'A human fetal lung cell atlas uncovers proximal-distal gradients of differentiation and key regulators of epithelial fates',
  'dataset_title': 'Endothelium',
  'collection_doi_label': 'He et al. (2022) Cell'},
 '6e00ccf7-0749-46ef-a999-dba785630d52': {'dataset_total_cell_count': 5499,
  'collection_name': 'Single cell transcriptomic profiling identifies molecular phenotypes of newborn human lung cells',
  'dataset_title': 'Single cell transcriptomic profiling identifies molecular phenotypes of newborn human lung cells',
  'collection_doi_label': 'Bhattacharya et al. (2024) Genes'},
 'ef1a4b05-540c-4f73-8ceb-49dfa800645d': {'dataset_total_cell_count': 5594,
  'collection_name': 'Transcriptomic Analysis of Air-Liquid Interface Culture in Human Lung Organoids Reveals Regulators of Epithelial Differentiation',
  'dataset_title': 'Transcriptomic Analysis of Air-Liquid Interface Culture in Human Lung Organoids Reveals Regulators of Epithelial Differentiation',
  'collection_doi_label': 'Kim et al. (2024) Cells'},
 '84230ea4-998d-4aa8-8456-81dd54ce23af': {'dataset_total_cell_count': 5608,
  'collection_name': 'Longitudinal profiling of respiratory and systemic immune responses reveals myeloid cell-driven lung inflammation in severe COVID-19',
  'dataset_title': '74 years old female - Fresh PBMCs (3 days post-intubation)',
  'collection_doi_label': 'Szabo et al. (2021) Immunity'},
 'ed9e9f96-4f08-49d2-bef5-b2c29adf3edc': {'dataset_total_cell_count': 5696,
  'collection_name': 'Longitudinal profiling of respiratory and systemic immune responses reveals myeloid cell-driven lung inflammation in severe COVID-19',
  'dataset_title': '66 years old female - Fresh PBMCs (4 days post-intubation)',
  'collection_doi_label': 'Szabo et al. (2021) Immunity'},
 '492d9f77-c4c8-485d-92d7-7686fe6c8482': {'dataset_total_cell_count': 5834,
  'collection_name': 'Longitudinal profiling of respiratory and systemic immune responses reveals myeloid cell-driven lung inflammation in severe COVID-19',
  'dataset_title': '74 years old female - Airway Wash (3 days post-intubation)',
  'collection_doi_label': 'Szabo et al. (2021) Immunity'},
 '248cf7bf-508b-4c28-a2fd-cabe2ab956aa': {'dataset_total_cell_count': 5980,
  'collection_name': 'Single-cell transcriptome analysis reveals differential nutrient absorption functions in human intestine',
  'dataset_title': 'Ileum',
  'collection_doi_label': 'Wang et al. (2020) Journal of Experimental Medicine'},
 'f801b7a9-80a6-4d09-9161-71474deb58ae': {'dataset_total_cell_count': 6044,
  'collection_name': 'Single-cell analyses of renal cell cancers reveal insights into tumor microenvironment, cell of origin, and therapy response',
  'dataset_title': 'normal - Single-cell analyses of renal cell cancers reveal insights into tumor microenvironment, cell of origin, and therapy response',
  'collection_doi_label': 'Zhang et al. (2021) Proc. Natl. Acad. Sci. U.S.A.'},
 '0de831e0-a525-4ec5-b717-df56f2de2bf0': {'dataset_total_cell_count': 6133,
  'collection_name': 'HVS: Human variation study',
  'dataset_title': 'L56NP - neocortex: Human variation study (HVS)',

## data info from cellxgene census

In [4]:
latest_census = cellxgene_census.open_soma(census_version = "latest")
latest_census_datasets = latest_census["census_info"]["datasets"].read().concat().to_pandas()
latest_census_datasets

,soma_joinid,citation,collection_id,collection_name,collection_doi,collection_doi_label,dataset_id,dataset_version_id,dataset_title,dataset_h5ad_path,dataset_total_cell_count
0,0,Publication: https://doi.org/10.1016/j.isci.20...,8e880741-bf9a-4c8e-9227-934204631d2a,High Resolution Slide-seqV2 Spatial Transcript...,10.1016/j.isci.2022.104097,Marshall et al. (2022) iScience,4eb29386-de81-452f-b3c0-e00844e8c7fd,66699060-0389-4fbd-b3a5-196b3b4e32d6,Spatial transcriptomics in mouse: Puck_191112_05,4eb29386-de81-452f-b3c0-e00844e8c7fd.h5ad,10888
1,1,Publication: https://doi.org/10.1016/j.isci.20...,8e880741-bf9a-4c8e-9227-934204631d2a,High Resolution Slide-seqV2 Spatial Transcript...,10.1016/j.isci.2022.104097,Marshall et al. (2022) iScience,78d59e4a-82eb-4a61-a1dc-da974d7ea54b,f64950a2-a3c8-490a-8431-7121eeb4f5f4,Spatial transcriptomics in mouse: Puck_191112_08,78d59e4a-82eb-4a61-a1dc-da974d7ea54b.h5ad,10250
2,2,Publication: https://doi.org/10.1016/j.isci.20...,8e880741-bf9a-4c8e-9227-934204631d2a,High Resolution Slide-seqV2 Spatial Transcript...,10.1016/j.isci.2022.104097,Marshall et al. (2022) iScience,add5eb84-5fc9-4f01-982e-a346dd42ee82,781a724a-b0f5-46c4-9a13-e6293ef4364f,Spatial transcriptomics in mouse: Puck_191109_20,add5eb84-5fc9-4f01-982e-a346dd42ee82.h5ad,12906
3,3,Publication: https://doi.org/10.1016/j.isci.20...,8e880741-bf9a-4c8e-9227-934204631d2a,High Resolution Slide-seqV2 Spatial Transcript...,10.1016/j.isci.2022.104097,Marshall et al. (2022) iScience,b020294c-ab82-4547-b5a7-63d8ffa575ed,96a79598-297b-4ade-a6c1-a431ab243548,Spatial transcriptomics in mouse: Puck_191112_13,b020294c-ab82-4547-b5a7-63d8ffa575ed.h5ad,15161
4,4,Publication: https://doi.org/10.1038/s41591-02...,a96133de-e951-4e2d-ace6-59db8b3bfb1d,HTAN/HTAPP Broad - Spatio-molecular dissection...,10.1038/s41591-024-03215-z,Klughammer et al. (2024) Nat Med,d7476ae2-e320-4703-8304-da5c42627e71,ac9fe945-6784-48fa-a2d5-a8646196d37e,HTAPP-330-SMP-1082 scRNA-seq,d7476ae2-e320-4703-8304-da5c42627e71.h5ad,565
...,...,...,...,...,...,...,...,...,...,...,...
1841,1841,Publication: https://doi.org/10.1038/s41586-02...,45d5d2c3-bc28-4814-aed6-0bb6f0e11c82,A single-cell transcriptional timelapse of mou...,10.1038/s41586-024-07069-w,Qiu et al. (2024) Nature,dcfa2614-7ca7-4d82-814c-350626eccb26,ca20ef35-13c0-4850-bec4-ba00e6bbd6f9,Major cell cluster: Mesoderm,dcfa2614-7ca7-4d82-814c-350626eccb26.h5ad,3267338
1842,1842,Publication: https://doi.org/10.1126/science.a...,e5f58829-1a66-40b5-a624-9046778e74f5,Tabula Sapiens,10.1126/science.abl4896,The Tabula Sapiens Consortium* et al. (2022) S...,53d208b0-2cfd-4366-9866-c3c6114081bc,5a495302-b7cd-4bf9-853e-95627b00bb03,Tabula Sapiens - All Cells,53d208b0-2cfd-4366-9866-c3c6114081bc.h5ad,1136218
1843,1843,Publication: https://doi.org/10.1038/s41586-02...,45d5d2c3-bc28-4814-aed6-0bb6f0e11c82,A single-cell transcriptional timelapse of mou...,10.1038/s41586-024-07069-w,Qiu et al. (2024) Nature,dcfd4feb-18a3-4b30-81d7-1b0c544a8ab3,a5a85963-8004-41a1-8eb5-ca65266d89c3,Whole dataset: Raw counts only,dcfd4feb-18a3-4b30-81d7-1b0c544a8ab3.h5ad,11441407
1844,1844,Publication: https://doi.org/10.1038/s41593-02...,1ca90a2d-2943-483d-b678-b809bf464c30,SEA-AD: Seattle Alzheimer’s Disease Brain Cell...,10.1038/s41593-024-01774-5,Gabitto et al. (2024) Nat Neurosci,c2876b1b-06d8-4d96-a56b-5304f815b99a,92b37feb-aa2c-40d7-bd90-0a9b5ddb3b27,Whole Taxonomy - MTG: Seattle Alzheimer's Dise...,c2876b1b-06d8-4d96-a56b-5304f815b99a.h5ad,1378211
1845,1845,Publication: https://doi.org/10.1038/s41593-02...,1ca90a2d-2943-483d-b678-b809bf464c30,SEA-AD: Seattle Alzheimer’s Disease Brain Cell...,10.1038/s41593-024-01774-5,Gabitto et al. (2024) Nat Neurosci,6f7fd0f1-a2ed-4ff1-80d3-33dde731cbc3,dad4819b-4c14-439c-b32a-2c8d68bd22e1,Whole Taxonomy - DLPFC: Seattle Alzheimer's Di...,6f7fd0f1-a2ed-4ff1-80d3-33dde731cbc3.h5ad,1395601

In [12]:
info_df = latest_census_datasets[["dataset_id", "collection_doi_label", "collection_doi", "dataset_title"]]
info_df

,dataset_id,collection_doi_label,collection_doi,dataset_title
0,4eb29386-de81-452f-b3c0-e00844e8c7fd,Marshall et al. (2022) iScience,10.1016/j.isci.2022.104097,Spatial transcriptomics in mouse: Puck_191112_05
1,78d59e4a-82eb-4a61-a1dc-da974d7ea54b,Marshall et al. (2022) iScience,10.1016/j.isci.2022.104097,Spatial transcriptomics in mouse: Puck_191112_08
2,add5eb84-5fc9-4f01-982e-a346dd42ee82,Marshall et al. (2022) iScience,10.1016/j.isci.2022.104097,Spatial transcriptomics in mouse: Puck_191109_20
3,b020294c-ab82-4547-b5a7-63d8ffa575ed,Marshall et al. (2022) iScience,10.1016/j.isci.2022.104097,Spatial transcriptomics in mouse: Puck_191112_13
4,d7476ae2-e320-4703-8304-da5c42627e71,Klughammer et al. (2024) Nat Med,10.1038/s41591-024-03215-z,HTAPP-330-SMP-1082 scRNA-seq
...,...,...,...,...
1841,dcfa2614-7ca7-4d82-814c-350626eccb26,Qiu et al. (2024) Nature,10.1038/s41586-024-07069-w,Major cell cluster: Mesoderm
1842,53d208b0-2cfd-4366-9866-c3c6114081bc,The Tabula Sapiens Consortium* et al. (2022) S...,10.1126/science.abl4896,Tabula Sapiens - All Cells
1843,dcfd4feb-18a3-4b30-81d7-1b0c544a8ab3,Qiu et al. (2024) Nature,10.1038/s41586-024-07069-w,Whole dataset: Raw counts only
1844,c2876b1b-06d8-4d96-a56b-5304f815b99a,Gabitto et al. (2024) Nat Neurosci,10.1038/s41593-024-01774-5,Whole Taxonomy - MTG: Seattle Alzheimer's Dise...
1845,6f7fd0f1-a2ed-4ff1-80d3-33dde731cbc3,Gabitto et al. (2024) Nat Neurosci,10.1038/s41593-024-01774-5,Whole Taxonomy - DLPFC: Seattle Alzheimer's Di...

## Load metadata

In [8]:
data = pd.read_csv(metadata_file, sep ='\t')
data.columns

/tmp/ipykernel_3599/1706137700.py:1: DtypeWarning: Columns (1,2,3,4,6,7,8,9,11,17,18,19,20,21,22) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv(metadata_file, sep ='\t')

Index(['new_index', 'assay_differentiation', 'assay_type_differentiation',
       'bio_sample', 'cell_line', 'cell_type_original', 'gm', 'id',
       'individual', 'state_exact', 'suspension_type', 'tech_sample',
       'treatment', 'organoid_age_days', 'publication', 'doi', 'batch',
       'annot_level_1', 'annot_level_2', 'annot_level_3_rev2',
       'annot_level_4_rev2', 'annot_region_rev2', 'annot_ntt_rev2',
       'Hallmark_Glycolysis', 'hnoca_core', 'annot_level_2_extended',
       'tissue_type', 'sex_ontology_term_id', 'donor_id',
       'assay_ontology_term_id', 'self_reported_ethnicity_ontology_term_id',
       'tissue_ontology_term_id', 'disease_ontology_term_id',
       'development_stage_ontology_term_id', 'cell_type_ontology_term_id',
       'is_primary_data', 'cell_type', 'assay', 'disease', 'sex', 'tissue',
       'self_reported_ethnicity', 'development_stage', 'observation_joinid',
       'dataset_id', 'n_genes', 'collection'],
      dtype='object')

## annotate metadata with publication information

In [7]:
data = data.merge(info_df, on='dataset_id', how='left')
data

,new_index,assay_differentiation,assay_type_differentiation,bio_sample,cell_line,cell_type_original,gm,id,individual,state_exact,...,self_reported_ethnicity,development_stage,observation_joinid,dataset_id,n_genes,collection,dataset_total_cell_count,collection_name,dataset_title,collection_doi_label
0,d7f5d8d0-6150-48d7-b094-c34286ad11a1_cell_0_99...,"Andersen, 2020 (doi: 10.1016/j.cell.2020.11.017)",guided,homosapiens_hindbrain_2020_bdrhapsodywholetran...,custom_8858-1,unknown,unknown,homosapiens_hindbrain_2020_bdrhapsodywholetran...,unknown,unknown,...,unknown,22-year-old stage,s)tQB!LM7n,d7f5d8d0-6150-48d7-b094-c34286ad11a1,1871,He et al. (2024) Nature,NaN,NaN,NaN,NaN
1,d7f5d8d0-6150-48d7-b094-c34286ad11a1_cell_0_99...,"Andersen, 2020 (doi: 10.1016/j.cell.2020.11.017)",guided,homosapiens_hindbrain_2020_bdrhapsodywholetran...,custom_8858-1,unknown,unknown,homosapiens_hindbrain_2020_bdrhapsodywholetran...,unknown,unknown,...,unknown,22-year-old stage,^+Yefv?=rp,d7f5d8d0-6150-48d7-b094-c34286ad11a1,1676,He et al. (2024) Nature,NaN,NaN,NaN,NaN
2,d7f5d8d0-6150-48d7-b094-c34286ad11a1_cell_0_99...,"Andersen, 2020 (doi: 10.1016/j.cell.2020.11.017)",guided,homosapiens_hindbrain_2020_bdrhapsodywholetran...,custom_8858-1,unknown,unknown,homosapiens_hindbrain_2020_bdrhapsodywholetran...,unknown,unknown,...,unknown,22-year-old stage,XT%?7@JAv*,d7f5d8d0-6150-48d7-b094-c34286ad11a1,1924,He et al. (2024) Nature,NaN,NaN,NaN,NaN
3,d7f5d8d0-6150-48d7-b094-c34286ad11a1_cell_0_99...,"Andersen, 2020 (doi: 10.1016/j.cell.2020.11.017)",guided,homosapiens_hindbrain_2020_bdrhapsodywholetran...,custom_8858-1,unknown,unknown,homosapiens_hindbrain_2020_bdrhapsodywholetran...,unknown,unknown,...,unknown,22-year-old stage,o-Jqb5)$mk,d7f5d8d0-6150-48d7-b094-c34286ad11a1,1636,He et al. (2024) Nature,NaN,NaN,NaN,NaN
4,d7f5d8d0-6150-48d7-b094-c34286ad11a1_cell_0_99...,"Andersen, 2020 (doi: 10.1016/j.cell.2020.11.017)",guided,homosapiens_hindbrain_2020_bdrhapsodywholetran...,custom_8858-1,unknown,unknown,homosapiens_hindbrain_2020_bdrhapsodywholetran...,unknown,unknown,...,unknown,22-year-old stage,h%Knua-p<V,d7f5d8d0-6150-48d7-b094-c34286ad11a1,1733,He et al. (2024) Nature,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1920449,d7f5d8d0-6150-48d7-b094-c34286ad11a1_cell_1920...,NaN,NaN,NaN,NaN,unknown,NaN,NaN,NaN,NaN,...,unknown,blastula stage,-d_t|seg;^,d7f5d8d0-6150-48d7-b094-c34286ad11a1,2522,He et al. (2024) Nature,NaN,NaN,NaN,NaN
1920450,d7f5d8d0-6150-48d7-b094-c34286ad11a1_cell_1920...,NaN,NaN,NaN,NaN,unknown,NaN,NaN,NaN,NaN,...,unknown,blastula stage,qcI~V4D+t(,d7f5d8d0-6150-48d7-b094-c34286ad11a1,1407,He et al. (2024) Nature,NaN,NaN,NaN,NaN
1920451,d7f5d8d0-6150-48d7-b094-c34286ad11a1_cell_1920...,NaN,NaN,NaN,NaN,unknown,NaN,NaN,NaN,NaN,...,unknown,blastula stage,h#~LNChcqg,d7f5d8d0-6150-48d7-b094-c34286ad11a1,2876,He et al. (2024) Nature,NaN,NaN,NaN,NaN
1920452,d7f5d8d0-6150-48d7-b094-c34286ad11a1_cell_1920...,NaN,NaN,NaN,NaN,unknown,NaN,NaN,NaN,NaN,...,unknown,blastula stage,lbS`~YGFHX,d7f5d8d0-6150-48d7-b094-c34286ad11a1,1733,He et al. (2024) Nature,NaN,NaN,NaN,NaN
1920453,d7f5d8d0-6150-48d7-b094-c34286ad11a1_cell_1920...,NaN,NaN,NaN,NaN,unknown,NaN,NaN,NaN,NaN,...,unknown,blastula stage,B1;lolYc{Y,d7f5d8d0-6150-48d7-b094-c34286ad11a1,2044,He et al. (2024) Nature,NaN,NaN,NaN,NaN

In [16]:
data["collection_doi"].nunique()

79

## custom composite new column for cell type

In [10]:
#composite new column

# Define your conditions
conditions = [
    data["publication_label"] == "Gabitto et al. (2024) Nat Neurosci",
    data["publication_label"] == "Siletti et al. (2023) Science",
    data["publication_label"] == "BICAN Basal Ganglia",
]

# Define the corresponding column to pull from
choices = [
    data["cell_type"],
    data["supercluster_term"],
    data["Group"],
]

# Create the new column
data["Gabitto_cell_type/Siletti_supercluster/BG_group"] = np.select(
    conditions, choices, default=""
)

In [4]:
metadata_file = "combined_UCE_5neuro/obs_anno.tsv"
data = pd.read_csv(metadata_file, sep ='\t')
data.columns

/tmp/ipykernel_4290/3338614073.py:2: DtypeWarning: Columns (1,2,3,4,5,6,7,8,9,13,14,16,17,18,19,20,21,72,73,74,75,76,78,79,80,81,82,84,85,86,88,90,91,92,94,96,97,98,100,102,103,104,108,109,110,111,112,113,114,115,120,121,123,124,125,126,127,128,129,131,132,139,140) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv(metadata_file, sep ='\t')

Index(['new_index', 'old_index', 'Neighborhood', 'Class', 'Subclass', 'Group',
       'Cluster', 'cluster_id', 'cell_type_ontology_term', 'load_id',
       ...
       'raw_sum', 'nnz', 'raw_mean_nnz', 'raw_variance_nnz', 'n_measured_vars',
       'publication_label', 'doi', 'doi_date', 'dataset_title',
       'Gabitto_cell_type/Siletti_supercluster/BG_group'],
      dtype='object', length=143)

In [9]:
#composite new column

# Define your conditions
conditions = [
    data["publication_label"] == "Gabitto et al. (2024) Nat Neurosci",
    data["publication_label"] == "Siletti et al. (2023) Science",
    data["publication_label"] == "BICAN Basal Ganglia",
]

# Define the corresponding column to pull from
choices = [
    data["cell_type_ontology_term_id"],
    data["cell_type_ontology_term_id"],
    data["CL:ID_group"],
]

# Create the new column
data["CL"] = np.select(
    conditions, choices, default=""
)

# Keep only values starting with "CL:"; everything else -> ""
data["CL"] = data["CL"].where(data["CL"].astype(str).str.startswith("CL:"), "")

In [10]:
unique_rows = data[["CL", "Gabitto_cell_type/Siletti_supercluster/BG_group"]].drop_duplicates()
print(unique_rows.to_string(index=False))

        CL                    Gabitto_cell_type/Siletti_supercluster/BG_group
CL:4023051                                                               VLMC
CL:0000128                                                       Oligo OPALIN
CL:0000129                                                          Microglia
CL:0000127                                                          Astrocyte
CL:4030051                                                        STRv D1 MSN
CL:0000128                                                      Oligo PLEKHG1
CL:4030047                                                 STRd D2 Matrix MSN
CL:0002453                                                                OPC
CL:4030043                                                 STRd D1 Matrix MSN
CL:4030049                                              STRd D2 Striosome MSN
CL:4030052                                                        STRv D2 MSN
CL:4042001                                                STR TAC3-PLPP4 GABA
CL:4030050                                                STR D1D2 Hybrid MSN
                                                                      ImAstro
                                                         GPe SOX6-CTXND1 GABA
                                                           AMY-SLEA-BNST GABA
CL:4030054                                                  STRv D1 NUDAP MSN
CL:4030048                                              STRd D1 Striosome MSN
CL:4042023                                            STR FS PTHLH-PVALB GABA
                                                  STRd D2 StrioMat Hybrid MSN
CL:0000669                                                           Pericyte
                                                  STR-BF TAC3-PLPP4-LHX8 GABA
                                                           STR SST-CHODL GABA
CL:4042031                                                            ImOligo
                                                           STR SST-RSPO2 GABA
                                                          GPe MEIS2-SOX6 GABA
CL:4023059                                                                COP
CL:4030053                                                          OT D1 ICj
                                                                  ZI-HTH GABA
CL:0000115                                                               Endo
CL:4042003                                                                BAM
CL:0000084                                                            T cells
                                                                      B cells
                                                              LAMP5-LHX6 GABA
                                                                     VIP GABA
                                                                OB FRMD7 GABA
                                                                 VTR-HTH Glut
                                                            LAMP5-CXCL14 GABA
                                                         STR Cholinergic GABA
CL:0000192                                                                SMC
                                                                     Monocyte
                                               GPe-NDB-SI LHX6-LHX8-GBX1 GABA
                                                         STR LYPD6-RSPO2 GABA
CL:0000065                                                          Ependymal
                                                                BF SKOR1 Glut
                                                        STRd Cholinergic GABA
                                                                 OB Dopa-GABA
                                                     GPin-BF Cholinergic GABA
                                                 SN-VTR-HTH GATA3-TCF7L2 GABA
                                                        AMY-SLEA-BNST D1 GABA
CL:4042025                                                       SN SOX6 Dopa
                                                                     GPi Core
                                                         STH PVALB-PITX2 Glut
                                                          STR SST-ADARB2 GABA
                                                                    GPi Shell
CL:4042025                                                  SN-VTR CALB1 Dopa
                                                                 SN EBF2 GABA
                                                             SN-VTR GAD2 Dopa
                                                          SN GATA3-PVALB GABA
                                                               SN SEMA5A GABA
CL:0000540                                                  Upper rhombic lip
CL:0000540                                                           Splatter
CL:0000540                                                  Lower rhombic lip
CL:0000540                                                    Mammillary body
CL:0000540                                                Thalamic excitatory
CL:0000540                                                Amygdala excitatory
CL:0000540                                                Medium spiny neuron
CL:0000540                                      Eccentric medium spiny neuron
CL:0000540                                                      Miscellaneous
CL:0000540                                              Cerebellar inhibitory
CL:0000540                                        Midbrain-derived inhibitory
CL:0000540                                                    CGE interneuron
CL:0000540                                          LAMP5-LHX6 and Chandelier
CL:0000540                                                    MGE interneuron
CL:0000540                                         Deep-layer near-projecting
CL:0000540                                  Deep-layer corticothalamic and 6b
CL:0000540                                                  Hippocampal CA1-3
CL:0000540                                     Upper-layer intratelencephalic
CL:0000540                                      Deep-layer intratelencephalic
CL:0000540                                          Hippocampal dentate gyrus
CL:0000540                                                    Hippocampal CA4
CL:0000738                                                      Miscellaneous
CL:0000128                                                    Oligodendrocyte
CL:0000128                                Committed oligodendrocyte precursor
CL:0000644                                                      Bergmann glia
CL:0002453                                          Oligodendrocyte precursor
CL:0000706                                                     Choroid plexus
CL:0000057                                                         Fibroblast
CL:0000669                                                           Vascular
CL:0000359                                                           Vascular
CL:0000115                                                           Vascular
CL:0000878                                                          Microglia
CL:0000128                                                    oligodendrocyte
CL:4023040 L2/3-6 intratelencephalic projecting glutamatergic cortical neuron
CL:4023012                      near-projecting glutamatergic cortical neuron
CL:0002453                                     oligodendrocyte precursor cell
CL:4023018                               pvalb GABAergic cortical interneuron
CL:4023017                                 sst GABAergic cortical interneuron
CL:4023011                               lamp5 GABAergic cortical interneuron
CL:0002605                                   astrocyte of the cerebral cortex
CL:4023016                                 vip GABAergic cortical interneuron
CL:4023051                                       vascular leptomeningeal cell
CL:0000129                                                    microglial cell
CL:4023038                                  L6b glutamatergic cortical neuron
CL:4023015                                sncg GABAergic cortical interneuron
CL:4023013           corticothalamic-projecting glutamatergic cortical neuron
CL:4023036                    chandelier pvalb GABAergic cortical interneuron
CL:4023070  caudal ganglionic eminence derived GABAergic cortical interneuron
CL:4023041     L5 extratelencephalic projecting glutamatergic cortical neuron
CL:1001602                                   cerebral cortex endothelial cell

In [11]:
mapping = {
    "Mammillary body": "CL:4023074",
    "Thalamic excitatory": "CL:4023068",
    "Amygdala excitatory": "CL:4023039",
    "Medium spiny neuron": "CL:1001474",
    "Eccentric medium spiny neuron": "CL:4030057",
    "Cerebellar inhibitory": "CL:4023057",
    "Midbrain-derived inhibitory":"CL:4023079",
    "CGE interneuron":"CL:4023064",
    "MGE interneuron":"CL:4023063",
    "Deep-layer near-projecting":"CL:4030067",
    "Deep-layer corticothalamic and 6b":"CL:4023042",
    "Hippocampal CA1-3":"CL:4023060",
    "Upper-layer intratelencephalic":"CL:4023008",
    "Deep-layer intratelencephalic":"CL:4023008",
    "Hippocampal dentate gyrus":"CL:4023062",
    "Hippocampal CA4":"CL:4023061",
}
data["CL"] = data["supercluster_term"].map(mapping).fillna(data["CL"])

In [12]:
unique_rows = data[["CL", "Gabitto_cell_type/Siletti_supercluster/BG_group"]].drop_duplicates()
print(unique_rows.to_string(index=False))

        CL                    Gabitto_cell_type/Siletti_supercluster/BG_group
CL:4023051                                                               VLMC
CL:0000128                                                       Oligo OPALIN
CL:0000129                                                          Microglia
CL:0000127                                                          Astrocyte
CL:4030051                                                        STRv D1 MSN
CL:0000128                                                      Oligo PLEKHG1
CL:4030047                                                 STRd D2 Matrix MSN
CL:0002453                                                                OPC
CL:4030043                                                 STRd D1 Matrix MSN
CL:4030049                                              STRd D2 Striosome MSN
CL:4030052                                                        STRv D2 MSN
CL:4042001                                                STR TAC3-PLPP4 GABA
CL:4030050                                                STR D1D2 Hybrid MSN
                                                                      ImAstro
                                                         GPe SOX6-CTXND1 GABA
                                                           AMY-SLEA-BNST GABA
CL:4030054                                                  STRv D1 NUDAP MSN
CL:4030048                                              STRd D1 Striosome MSN
CL:4042023                                            STR FS PTHLH-PVALB GABA
                                                  STRd D2 StrioMat Hybrid MSN
CL:0000669                                                           Pericyte
                                                  STR-BF TAC3-PLPP4-LHX8 GABA
                                                           STR SST-CHODL GABA
CL:4042031                                                            ImOligo
                                                           STR SST-RSPO2 GABA
                                                          GPe MEIS2-SOX6 GABA
CL:4023059                                                                COP
CL:4030053                                                          OT D1 ICj
                                                                  ZI-HTH GABA
CL:0000115                                                               Endo
CL:4042003                                                                BAM
CL:0000084                                                            T cells
                                                                      B cells
                                                              LAMP5-LHX6 GABA
                                                                     VIP GABA
                                                                OB FRMD7 GABA
                                                                 VTR-HTH Glut
                                                            LAMP5-CXCL14 GABA
                                                         STR Cholinergic GABA
CL:0000192                                                                SMC
                                                                     Monocyte
                                               GPe-NDB-SI LHX6-LHX8-GBX1 GABA
                                                         STR LYPD6-RSPO2 GABA
CL:0000065                                                          Ependymal
                                                                BF SKOR1 Glut
                                                        STRd Cholinergic GABA
                                                                 OB Dopa-GABA
                                                     GPin-BF Cholinergic GABA
                                                 SN-VTR-HTH GATA3-TCF7L2 GABA
                                                        AMY-SLEA-BNST D1 GABA
CL:4042025                                                       SN SOX6 Dopa
                                                                     GPi Core
                                                         STH PVALB-PITX2 Glut
                                                          STR SST-ADARB2 GABA
                                                                    GPi Shell
CL:4042025                                                  SN-VTR CALB1 Dopa
                                                                 SN EBF2 GABA
                                                             SN-VTR GAD2 Dopa
                                                          SN GATA3-PVALB GABA
                                                               SN SEMA5A GABA
CL:0000540                                                  Upper rhombic lip
CL:0000540                                                           Splatter
CL:0000540                                                  Lower rhombic lip
CL:4023074                                                    Mammillary body
CL:4023068                                                Thalamic excitatory
CL:4023039                                                Amygdala excitatory
CL:1001474                                                Medium spiny neuron
CL:4030057                                      Eccentric medium spiny neuron
CL:0000540                                                      Miscellaneous
CL:4023057                                              Cerebellar inhibitory
CL:4023079                                        Midbrain-derived inhibitory
CL:4023064                                                    CGE interneuron
CL:0000540                                          LAMP5-LHX6 and Chandelier
CL:4023063                                                    MGE interneuron
CL:4030067                                         Deep-layer near-projecting
CL:4023042                                  Deep-layer corticothalamic and 6b
CL:4023060                                                  Hippocampal CA1-3
CL:4023008                                     Upper-layer intratelencephalic
CL:4023008                                      Deep-layer intratelencephalic
CL:4023062                                          Hippocampal dentate gyrus
CL:4023061                                                    Hippocampal CA4
CL:0000738                                                      Miscellaneous
CL:0000128                                                    Oligodendrocyte
CL:0000128                                Committed oligodendrocyte precursor
CL:0000644                                                      Bergmann glia
CL:0002453                                          Oligodendrocyte precursor
CL:0000706                                                     Choroid plexus
CL:0000057                                                         Fibroblast
CL:0000669                                                           Vascular
CL:0000359                                                           Vascular
CL:0000115                                                           Vascular
CL:0000878                                                          Microglia
CL:0000128                                                    oligodendrocyte
CL:4023040 L2/3-6 intratelencephalic projecting glutamatergic cortical neuron
CL:4023012                      near-projecting glutamatergic cortical neuron
CL:0002453                                     oligodendrocyte precursor cell
CL:4023018                               pvalb GABAergic cortical interneuron
CL:4023017                                 sst GABAergic cortical interneuron
CL:4023011                               lamp5 GABAergic cortical interneuron
CL:0002605                                   astrocyte of the cerebral cortex
CL:4023016                                 vip GABAergic cortical interneuron
CL:4023051                                       vascular leptomeningeal cell
CL:0000129                                                    microglial cell
CL:4023038                                  L6b glutamatergic cortical neuron
CL:4023015                                sncg GABAergic cortical interneuron
CL:4023013           corticothalamic-projecting glutamatergic cortical neuron
CL:4023036                    chandelier pvalb GABAergic cortical interneuron
CL:4023070  caudal ganglionic eminence derived GABAergic cortical interneuron
CL:4023041     L5 extratelencephalic projecting glutamatergic cortical neuron
CL:1001602                                   cerebral cortex endothelial cell

In [14]:
# Select and rename columns
out = data[["CL", "Gabitto_cell_type/Siletti_supercluster/BG_group"]].rename(
    columns={
        "CL": "cell_type_ontology_term_id",   # or whatever new name you want
        "Gabitto_cell_type/Siletti_supercluster/BG_group": "cell_type"
    }
)
# Export to TSV
out.to_csv("combined_UCE_5neuro/prediction_obs.tsv", sep="\t", index=False)

# output

In [12]:
data.to_csv(out_file, sep="\t", index=False)