## This is the code to retrieve new human dataset IDs with primary_data

In [1]:
import cellxgene_census ##python 3.11 kernel
import pandas as pd
import numpy as np
import os,re, sys

In [26]:
embedding="UCE"
#embedding= "scimilarity"

In [2]:
#census_version="2023-12-15" # Universal Cell Embeddings (UCE) run on this release
#census = cellxgene_census.open_soma(census_version = census_version)
latest_census = cellxgene_census.open_soma(census_version = "latest")
stable_census = cellxgene_census.open_soma(census_version = "stable")
latest_census,stable_census

The "stable" release is currently 2025-01-30. Specify 'census_version="2025-01-30"' in future calls to open_soma() to ensure data consistency.

(<Collection 's3://cellxgene-census-public-us-west-2/cell-census/2025-11-17/soma/' (open for 'r') (3 items)
     'census_data': 's3://cellxgene-census-public-us-west-2/cell-census/2025-11-17/soma/census_data' (unopened)
     'census_info': 's3://cellxgene-census-public-us-west-2/cell-census/2025-11-17/soma/census_info' (unopened)
     'census_spatial_sequencing': 's3://cellxgene-census-public-us-west-2/cell-census/2025-11-17/soma/census_spatial_sequencing' (unopened)>,
 <Collection 's3://cellxgene-census-public-us-west-2/cell-census/2025-01-30/soma/' (open for 'r') (3 items)
     'census_data': 's3://cellxgene-census-public-us-west-2/cell-census/2025-01-30/soma/census_data' (unopened)
     'census_info': 's3://cellxgene-census-public-us-west-2/cell-census/2025-01-30/soma/census_info' (unopened)
     'census_spatial_sequencing': 's3://cellxgene-census-public-us-west-2/cell-census/2025-01-30/soma/census_spatial_sequencing' (unopened)>)

In [3]:
print(latest_census["census_info"])

<Collection 's3://cellxgene-census-public-us-west-2/cell-census/2025-11-17/soma/census_info' (open for 'r') (4 items)
    'datasets': 's3://cellxgene-census-public-us-west-2/cell-census/2025-11-17/soma/census_info/datasets' (unopened)
    'organisms': 's3://cellxgene-census-public-us-west-2/cell-census/2025-11-17/soma/census_info/organisms' (unopened)
    'summary': 's3://cellxgene-census-public-us-west-2/cell-census/2025-11-17/soma/census_info/summary' (unopened)
    'summary_cell_counts': 's3://cellxgene-census-public-us-west-2/cell-census/2025-11-17/soma/census_info/summary_cell_counts' (unopened)>

## get specific dataset info

In [22]:
df = latest_census["census_info"]["datasets"].read().concat().to_pandas()
df

,soma_joinid,citation,collection_id,collection_name,collection_doi,collection_doi_label,dataset_id,dataset_version_id,dataset_title,dataset_h5ad_path,dataset_total_cell_count
0,0,Publication: https://doi.org/10.1016/j.isci.20...,8e880741-bf9a-4c8e-9227-934204631d2a,High Resolution Slide-seqV2 Spatial Transcript...,10.1016/j.isci.2022.104097,Marshall et al. (2022) iScience,4eb29386-de81-452f-b3c0-e00844e8c7fd,66699060-0389-4fbd-b3a5-196b3b4e32d6,Spatial transcriptomics in mouse: Puck_191112_05,4eb29386-de81-452f-b3c0-e00844e8c7fd.h5ad,10888
1,1,Publication: https://doi.org/10.1016/j.isci.20...,8e880741-bf9a-4c8e-9227-934204631d2a,High Resolution Slide-seqV2 Spatial Transcript...,10.1016/j.isci.2022.104097,Marshall et al. (2022) iScience,78d59e4a-82eb-4a61-a1dc-da974d7ea54b,f64950a2-a3c8-490a-8431-7121eeb4f5f4,Spatial transcriptomics in mouse: Puck_191112_08,78d59e4a-82eb-4a61-a1dc-da974d7ea54b.h5ad,10250
2,2,Publication: https://doi.org/10.1016/j.isci.20...,8e880741-bf9a-4c8e-9227-934204631d2a,High Resolution Slide-seqV2 Spatial Transcript...,10.1016/j.isci.2022.104097,Marshall et al. (2022) iScience,add5eb84-5fc9-4f01-982e-a346dd42ee82,781a724a-b0f5-46c4-9a13-e6293ef4364f,Spatial transcriptomics in mouse: Puck_191109_20,add5eb84-5fc9-4f01-982e-a346dd42ee82.h5ad,12906
3,3,Publication: https://doi.org/10.1016/j.isci.20...,8e880741-bf9a-4c8e-9227-934204631d2a,High Resolution Slide-seqV2 Spatial Transcript...,10.1016/j.isci.2022.104097,Marshall et al. (2022) iScience,b020294c-ab82-4547-b5a7-63d8ffa575ed,96a79598-297b-4ade-a6c1-a431ab243548,Spatial transcriptomics in mouse: Puck_191112_13,b020294c-ab82-4547-b5a7-63d8ffa575ed.h5ad,15161
4,4,Publication: https://doi.org/10.1038/s41591-02...,a96133de-e951-4e2d-ace6-59db8b3bfb1d,HTAN/HTAPP Broad - Spatio-molecular dissection...,10.1038/s41591-024-03215-z,Klughammer et al. (2024) Nat Med,d7476ae2-e320-4703-8304-da5c42627e71,ac9fe945-6784-48fa-a2d5-a8646196d37e,HTAPP-330-SMP-1082 scRNA-seq,d7476ae2-e320-4703-8304-da5c42627e71.h5ad,565
...,...,...,...,...,...,...,...,...,...,...,...
1841,1841,Publication: https://doi.org/10.1038/s41586-02...,45d5d2c3-bc28-4814-aed6-0bb6f0e11c82,A single-cell transcriptional timelapse of mou...,10.1038/s41586-024-07069-w,Qiu et al. (2024) Nature,dcfa2614-7ca7-4d82-814c-350626eccb26,ca20ef35-13c0-4850-bec4-ba00e6bbd6f9,Major cell cluster: Mesoderm,dcfa2614-7ca7-4d82-814c-350626eccb26.h5ad,3267338
1842,1842,Publication: https://doi.org/10.1126/science.a...,e5f58829-1a66-40b5-a624-9046778e74f5,Tabula Sapiens,10.1126/science.abl4896,The Tabula Sapiens Consortium* et al. (2022) S...,53d208b0-2cfd-4366-9866-c3c6114081bc,5a495302-b7cd-4bf9-853e-95627b00bb03,Tabula Sapiens - All Cells,53d208b0-2cfd-4366-9866-c3c6114081bc.h5ad,1136218
1843,1843,Publication: https://doi.org/10.1038/s41586-02...,45d5d2c3-bc28-4814-aed6-0bb6f0e11c82,A single-cell transcriptional timelapse of mou...,10.1038/s41586-024-07069-w,Qiu et al. (2024) Nature,dcfd4feb-18a3-4b30-81d7-1b0c544a8ab3,a5a85963-8004-41a1-8eb5-ca65266d89c3,Whole dataset: Raw counts only,dcfd4feb-18a3-4b30-81d7-1b0c544a8ab3.h5ad,11441407
1844,1844,Publication: https://doi.org/10.1038/s41593-02...,1ca90a2d-2943-483d-b678-b809bf464c30,SEA-AD: Seattle Alzheimer’s Disease Brain Cell...,10.1038/s41593-024-01774-5,Gabitto et al. (2024) Nat Neurosci,c2876b1b-06d8-4d96-a56b-5304f815b99a,92b37feb-aa2c-40d7-bd90-0a9b5ddb3b27,Whole Taxonomy - MTG: Seattle Alzheimer's Dise...,c2876b1b-06d8-4d96-a56b-5304f815b99a.h5ad,1378211
1845,1845,Publication: https://doi.org/10.1038/s41593-02...,1ca90a2d-2943-483d-b678-b809bf464c30,SEA-AD: Seattle Alzheimer’s Disease Brain Cell...,10.1038/s41593-024-01774-5,Gabitto et al. (2024) Nat Neurosci,6f7fd0f1-a2ed-4ff1-80d3-33dde731cbc3,dad4819b-4c14-439c-b32a-2c8d68bd22e1,Whole Taxonomy - DLPFC: Seattle Alzheimer's Di...,6f7fd0f1-a2ed-4ff1-80d3-33dde731cbc3.h5ad,1395601

In [30]:
df[df.collection_id == "1ca90a2d-2943-483d-b678-b809bf464c30"]

,soma_joinid,citation,collection_id,collection_name,collection_doi,collection_doi_label,dataset_id,dataset_version_id,dataset_title,dataset_h5ad_path,dataset_total_cell_count
298,298,Publication: https://doi.org/10.1038/s41593-02...,1ca90a2d-2943-483d-b678-b809bf464c30,SEA-AD: Seattle Alzheimer’s Disease Brain Cell...,10.1038/s41593-024-01774-5,Gabitto et al. (2024) Nat Neurosci,3e87b1fa-472a-401c-8fa8-f31c10437d5f,ecfd0bb7-d6c4-482e-8293-138390132dbc,Endothelial - MTG: Seattle Alzheimer's Disease...,3e87b1fa-472a-401c-8fa8-f31c10437d5f.h5ad,2069
363,363,Publication: https://doi.org/10.1038/s41593-02...,1ca90a2d-2943-483d-b678-b809bf464c30,SEA-AD: Seattle Alzheimer’s Disease Brain Cell...,10.1038/s41593-024-01774-5,Gabitto et al. (2024) Nat Neurosci,81e91ff8-f619-4ad1-a0c3-b45e1dc63f68,78a93bdd-a26c-4971-b1e1-c48c02dbb241,Sst Chodl - MTG: Seattle Alzheimer's Disease A...,81e91ff8-f619-4ad1-a0c3-b45e1dc63f68.h5ad,1496
410,410,Publication: https://doi.org/10.1038/s41593-02...,1ca90a2d-2943-483d-b678-b809bf464c30,SEA-AD: Seattle Alzheimer’s Disease Brain Cell...,10.1038/s41593-024-01774-5,Gabitto et al. (2024) Nat Neurosci,2ecc72f8-085f-4e86-8692-771f316c54f6,b73ac0d8-928f-4f8a-bfb4-f96baf1e87c5,Endothelial - DLPFC: Seattle Alzheimer's Disea...,2ecc72f8-085f-4e86-8692-771f316c54f6.h5ad,2575
453,453,Publication: https://doi.org/10.1038/s41593-02...,1ca90a2d-2943-483d-b678-b809bf464c30,SEA-AD: Seattle Alzheimer’s Disease Brain Cell...,10.1038/s41593-024-01774-5,Gabitto et al. (2024) Nat Neurosci,236baeda-5fdd-41bf-8e32-bae21ac7d435,7e819064-ada7-4dd8-abe2-c3d16b2fb8ad,VLMC - MTG: Seattle Alzheimer's Disease Atlas ...,236baeda-5fdd-41bf-8e32-bae21ac7d435.h5ad,4328
518,518,Publication: https://doi.org/10.1038/s41593-02...,1ca90a2d-2943-483d-b678-b809bf464c30,SEA-AD: Seattle Alzheimer’s Disease Brain Cell...,10.1038/s41593-024-01774-5,Gabitto et al. (2024) Nat Neurosci,fc0ceb80-d2d9-47c1-9d78-b0e45c64c500,4e584a91-fc22-4b32-a0e7-b33d3a7cc0ee,Sst Chodl - DLPFC: Seattle Alzheimer's Disease...,fc0ceb80-d2d9-47c1-9d78-b0e45c64c500.h5ad,1877
560,560,Publication: https://doi.org/10.1038/s41593-02...,1ca90a2d-2943-483d-b678-b809bf464c30,SEA-AD: Seattle Alzheimer’s Disease Brain Cell...,10.1038/s41593-024-01774-5,Gabitto et al. (2024) Nat Neurosci,2e5a9b5d-d31b-4e9f-a179-d5d70ba459fb,0616f3a2-dc5c-4098-88e2-657dcbf91b01,VLMC - DLPFC: Seattle Alzheimer's Disease Atla...,2e5a9b5d-d31b-4e9f-a179-d5d70ba459fb.h5ad,4860
617,617,Publication: https://doi.org/10.1038/s41593-02...,1ca90a2d-2943-483d-b678-b809bf464c30,SEA-AD: Seattle Alzheimer’s Disease Brain Cell...,10.1038/s41593-024-01774-5,Gabitto et al. (2024) Nat Neurosci,07428d73-fdea-4bd4-a801-94b00c4d961c,e88cdf6b-2e71-411f-8316-971af6b88322,L5 ET - MTG: Seattle Alzheimer's Disease Atlas...,07428d73-fdea-4bd4-a801-94b00c4d961c.h5ad,2590
909,909,Publication: https://doi.org/10.1038/s41593-02...,1ca90a2d-2943-483d-b678-b809bf464c30,SEA-AD: Seattle Alzheimer’s Disease Brain Cell...,10.1038/s41593-024-01774-5,Gabitto et al. (2024) Nat Neurosci,8c6ed88f-11bf-4159-bad7-ff41fb1e1eca,89d46169-6941-4831-886c-014505308701,Chandelier - MTG: Seattle Alzheimer's Disease ...,8c6ed88f-11bf-4159-bad7-ff41fb1e1eca.h5ad,10928
911,911,Publication: https://doi.org/10.1038/s41593-02...,1ca90a2d-2943-483d-b678-b809bf464c30,SEA-AD: Seattle Alzheimer’s Disease Brain Cell...,10.1038/s41593-024-01774-5,Gabitto et al. (2024) Nat Neurosci,f67f2cfa-ba45-4f77-8e26-64a15f666043,d557ec86-38de-4e34-ad0d-1f23cb5d3427,Pax6 - MTG: Seattle Alzheimer's Disease Atlas ...,f67f2cfa-ba45-4f77-8e26-64a15f666043.h5ad,9203
944,944,Publication: https://doi.org/10.1038/s41593-02...,1ca90a2d-2943-483d-b678-b809bf464c30,SEA-AD: Seattle Alzheimer’s Disease Brain Cell...,10.1038/s41593-024-01774-5,Gabitto et al. (2024) Nat Neurosci,6cda07c7-5d7a-41ba-9799-5bb73da25a60,1c6487ed-8f54-46da-89d2-121c67ef6bf2,L5 ET - DLPFC: Seattle Alzheimer's Disease Atl...,6cda07c7-5d7a-41ba-9799-5bb73da25a60.h5ad,4097
1085,1085,Publication: https://doi.org/10.1038/s41593-02...,1ca90a2d-2943-483d-b678-b809bf464c30,SEA-AD: Seattle Alzheimer’s Disease Brain Cell...,10.1038/s41593-024-01774-5,Gabitto et al. (2024) Nat Neurosci,0eccaf0c-19d2-4900-9962-899378adf8be,a6eecd69-7ab7-4896-b3e3-3ab56b1d8631,Pax6 - DLPFC: Seattle Alzheimer's Disease Atla...,0eccaf0c-19d2-4900-9962-899378adf8be.h5ad,9446
1143,1143,Publication: https://doi.org/10.1038/s41593-02...,1ca90a2d-2943-483d-b678-b809bf464c30,SEA-AD: Seattle Alzheimer’s Disease Brain Cell...,10.1038/s41593-024-01774-5,Gabitto et al. (2024) Nat Neurosci,5ae6ab72-1927-4d5b-9826-86be65791293,a2f0c178-cccd-4e34-bd2d-cb32682f0285,Sncg - MTG: Seattle Alzheimer's Disease Atlas ...,5ae6ab72-1927-4d5b-9826-86be65791293.h5ad,22168
1201,1201,Publication: https://doi.org/10.1038/s41593-02...,1ca90a2d-2943-483d-b678-b809bf464c30,SEA-AD: Seattle Alzheimer’s Disease Brain Cell...,10.1038/s41593-024-01774-5,Gabitto et al. (2024) Nat Neurosci,c76098ba-eed3-45b1-98f2-96fcac55ed18,c66e3198-c766-499e-a609-7b462a41295b,Microglia-PVM - MTG: Seattle Alzheimer's Disea...,c76098ba-eed3-45b1-98f2-96fcac55ed18.h5ad,40000
1206,1206,Publication: https://doi.org/10.1038/s41593-02...,1ca90a2d-2943-483d-b678-b809bf464c30,SEA-AD: Seattle Alzheimer’s Disease Brain Cell...,10.1038/s41593-024-01774-5,Gabitto et al. (2024) Nat Neurosci,0374f03c-62e2-4859-8a14-acb00b0627d5,e80bee9e-19e3-4954-a22a-124fe4e8e26e,Chandelier - DLPFC: Seattle Alzheimer's Diseas...,0374f03c-62e2-4859-8a14-acb00b0627d5.h5ad,15412
1225,1225,Publication: https://doi.org/10.1038/s41593-02...,1ca90a2d-2943-483d-b678-b809bf464c30,SEA-AD: Seattle Alzheimer’s Disease Brain Cell...,10.1038/s41593-024-01774-5,Gabitto et al. (2024) Nat Neurosci,e8ac3386-31d4-48ba-aa70-1bae0cf020e7,9d1b4f0f-ef28-46b0-8851-a699f80dd673,Lamp5 Lhx6 - MTG: Seattle Alzheimer's Disease ...,e8ac3386-31d4-48ba-aa70-1bae0cf020e7.h5ad,21443
1241,1241,Publication: https://doi.org/10.1038/s41593-02...,1ca90a2d-2943-483d-b678-b809bf464c30,SEA-AD: Seattle Alzheimer’s Disease Brain Cell...,10.1038/s41593-024-01774-5,Gabitto et al. (2024) Nat Neurosci,1c05b7ae-4dfb-4c1b-a441-4b23c04b169e,0d009a56-b542-40bd-a71e-d4d4f2af473f,OPC - MTG: Seattle Alzheimer's Disease Atlas (...,1c05b7ae-4dfb-4c1b-a441-4b23c04b169e.h5ad,32493
1251,1251,Publication: https://doi.org/10.1038/s41593-02...,1ca90a2d-2943-483d-b678-b809bf464c30,SEA-AD: Seattle Alzheimer’s Disease Brain Cell...,10.1038/s41593-024-01774-5,Gabitto et al. (2024) Nat Neurosci,75e6eee5-d0e3-4291-9360-f288ffe6c7c4,42825075-41fe-4499-aa8e-25e56f1677f7,L5/6 NP - MTG: Seattle Alzheimer's Disease Atl...,75e6eee5-d0e3-4291-9360-f288ffe6c7c4.h5ad,20741
1255,1255,Publication: https://doi.org/10.1038/s41593-02...,1ca90a2d-2943-483d-b678-b809bf464c30,SEA-AD: Seattle Alzheimer’s Disease Brain Cell...,10.1038/s41593-024-01774-5,Gabitto et al. (2024) Nat Neurosci,8a8aedcb-5bb3-453d-a9f0-f37951ae1515,698f26b0-db32-4fe4-b8a9-55b91e2d485b,L6b - MTG: Seattle Alzheimer's Disease Atlas (...,8a8aedcb-5bb3-453d-a9f0-f37951ae1515.h5ad,16227
1282,1282,Publication: https://doi.org/10.1038/s41593-02...,1ca90a2d-2943-483d-b678-b809bf464c30,SEA-AD: Seattle Alzheimer’s Disease Brain Cell...,10.1038/s41593-024-01774-5,Gabitto et al. (2024) Nat Neurosci,c19275f5-739e-4796-ad5d-b0830b760db1,4c02c25f-d4ea-4c80-b88a-532ce40f3411,L6 CT - MTG: Seattle Alzheimer's Disease Atlas...,c19275f5-739e-4796-ad5d-b0830b760db1.h5ad,18402
1291,1291,Publication: https://doi.org/10.1038/s41593-02...,1ca90a2d-2943-483d-b678-b809bf464c30,SEA-AD: Seattle Alzheimer’s Disease Brain Cell...,10.1038/s41593-024-01774-5,Gabitto et al. (2024) Nat Neurosci,58c43cc2-e00e-43c4-94eb-8501369264e1,cac72969-4e63-4c65-b45e-8840ac1c3668,OPC - DLPFC: Seattle Alzheimer's Disease Atlas...,58c43cc2-e00e-43c4-94eb-8501369264e1.h5ad,29041
1311,1311,Publication: https://doi.org/10.1038/s41593-02...,1ca90a2d-2943-483d-b678-b809bf464c30,SEA-AD: Seattle Alzheimer’s Disease Brain Cell...,10.1038/s41593-024-01774-5,Gabitto et al. (2024) Nat Neurosci,100c6145-7b0e-4ba6-81c1-ffebed0d1ac4,a3198428-dd16-4344-8564-3897c1ccdb4b,Microglia-PVM - DLPFC: Seattle Alzheimer's Dis...,100c6145-7b0e-4ba6-81c1-ffebed0d1ac4.h5ad,42486
1312,1312,Publication: https://doi.org/10.1038/s41593-02...,1ca90a2d-2943-483d-b678-b809bf464c30,SEA-AD: Seattle Alzheimer’s Disease Brain Cell...,10.1038/s41593-024-01774-5,Gabitto et al. (2024) Nat Neurosci,1c9f5c6b-73da-4d17-95de-df080ffe0df1,39b6701b-eb0a-4dc6-820b-1cd2c1b7ee48,L6 IT Car3 - DLPFC: Seattle Alzheimer's Diseas...,1c9f5c6b-73da-4d17-95de-df080ffe0df1.h5ad,13909
1336,1336,Publication: https://doi.org/10.1038/s41593-02...,1ca90a2d-2943-483d-b678-b809bf464c30,SEA-AD: Seattle Alzheimer’s Disease Brain Cell...,10.1038/s41593-024-01774-5,Gabitto et al. (2024) Nat Neurosci,b1d37bbd-9ae4-4404-b2f9-f2fe66750e4e,3002675b-cde5-4ea5-8488-aa5b0b20ae39,Sncg - DLPFC: Seattle Alzheimer's Disease Atla...,b1d37bbd-9ae4-4404-b2f9-f2fe66750e4e.h5ad,24792
1362,1362,Publication: https://doi.org/10.1038/s41593-02...,1ca90a2d-2943-483d-b678-b809bf464c30,SEA-AD: Seattle Alzheimer’s Disease Brain Cell...,10.1038/s41593-024-01774-5,Gabitto et al. (2024) Nat Neurosci,b8920ef5-7d22-497b-abca-a7a9eb76d79a,34f04772-7e91-4c6d-a91b-f63429a633d8,L5/6 NP - DLPFC: Seattle Alzheimer's Disease A...,b8920ef5-7d22-497b-abca-a7a9eb76d79a.h5ad,19191
1377,1377,Publication: https://doi.org/10.1038/s41593-02...,1ca90a2d-2943-483d-b678-b809bf464c30,SEA-AD: Seattle Alzheimer’s Disease Brain Cell...,10.1038/s41593-024-01774-5,Gabitto et al. (2024) Nat Neurosci,eec3e37d-ed41-4881-bc6e-aaf39a2c6eb0,ac31afa6-12e1-4dc5-b85e-dd6f7afb83e4,Lamp5 - MTG: Seattle Alzheimer's Disease Atlas...,eec3e37d-ed41-4881-bc6e-aaf39a2c6eb0.h5ad,42921
1381,1381,Publication: https://doi.org/10.1038/s41593-02...,1ca90a2d-2943-483d-b678-b809bf464c30,SEA-AD: Seattle Alzheimer’s Disease Brain Cell...,10.1038/s41593-024-01774-5,Gabitto et al. (2024) Nat Neurosci,79d485a8-b8b1-49f2-85aa-c44e5206aa53,3ad4bd7e-3585-44a0-83d2-627deb734447,L6 IT Car3 - MTG: Seattle Alzheimer's Disease ...,79d485a8-b8b1-49f2-85aa-c44e5206aa53.h5ad,26129
1387,1387,Publication: https://doi.org/10.1038/s41593-02...,1ca90a2d-2943-483d-b678-b809bf464c30,SEA-AD: Seattle Alzheimer’s Disease Brain Cell...,10.1038/s41593-024-01774-5,Gabitto et al. (2024) Nat Neurosci,a190b2e9-3796-4785-9a2f-013e2a9a43e6,606a8fa1-bf44-4bbc-be59-e84304a6d140,Lamp5 Lhx6 - DLPFC: Seattle Alzheimer's Diseas...,a190b2e9-3796-4785-9a2f-013e2a9a43e6.h5ad,22891
1407,1407,Publication: https://doi.org/10.1038/s41593-02...,1ca90a2d-2943-483d-b678-b809bf464c30,SEA-AD: Seattle Alzheimer’s Disease Brain Cell...,10.1038/s41593-024-01774-5,Gabitto et al. (2024) Nat Neurosci,d0ea3ec4-0f3b-4649-9146-1c0b5f303a55,c1d101a4-3cf8-4df3-b658-59a362ffff33,L6b - DLPFC: Seattle Alzheimer's Disease Atlas...,d0ea3ec4-0f3b-4649-9146-1c0b5f303a55.h5ad,18903
1458,1458,Publication: https://doi.org/10.1038/s41593-02...,1ca90a2d-2943-483d-b678-b809bf464c30,SEA-AD: Seattle Alzheimer’s Disease Brain Cell...,10.1038/s41593-024-01774-5,Gabitto et al. (2024) Nat Neurosci,146216e1-ec30-4fee-a1fb-25defe801e2d,55d41297-1b52-46ce-bc13-aa47c96534c3,Sst - MTG: Seattle Alzheimer's Disease Atlas (...,146216e1-ec30-4fee-a1fb-25defe801e2d.h5ad,58265
1475,1475,Publication: https://doi.org/10.1038/s41593-02...,1ca90a2d-2943-483d-b678-b809bf464c30,SEA-AD: Seattle Alzheimer’s Disease Brain Cell...,10.1038/s41593-024-01774-5,Gabitto et al. (2024) Nat Neurosci,5097d77d-08fa-4105-a18f-4072d61522a4,8d212dd7-c7eb-4e9e-9126-f5b90c1e72d6,Astrocyte - MTG: Seattle Alzheimer's Disease A...,5097d77d-08fa-4105-a18f-4072d61522a4.h5ad,70009
1498,1498,Publication: https://doi.org/10.1038/s41593-02...,1ca90a2d-2943-483d-b678-b809bf464c30,SEA-AD: Seattle Alzheimer’s Disease Brain Cell...,10.1038/s41593-024-01774-5,Gabitto et al. (2024) Nat Neurosci,a4e89c26-e8d4-4471-9b06-16a1405880f0,b5ff368a-ac00-429a-b48e-a6d74fbc93ac,L6 CT - DLPFC: Seattle Alzheimer's Disease Atl...,a4e89c26-e8d4-4471-9b06-16a1405880f0.h5ad,29343
1515,1515,Publication: https://doi.org/10.1038/s41593-02...,1ca90a2d-2943-483d-b678-b809bf464c30,SEA-AD: Seattle Alzheimer’s Disease Brain Cell...,10.1038/s41593-024-01774-5,Gabitto et al. (2024) Nat Neurosci,d2fc9880-e6d3-4922-af5c-61f4f517adfa,c5a54e52-b421-44be-a066-bbdfe8452bc1,Oligodendrocyte - MTG: Seattle Alzheimer's Dis...,d2fc9880-e6d3-4922-af5c-61f4f517adfa.h5ad,111194
1552,1552,Publication: https://doi.org/10.1038/s41593-02...,1ca90a2d-2943-483d-b678-b809bf464c30,SEA-AD: Seattle Alzheimer’s Disease Brain Cell...,10.1038/s41593-024-01774-5,Gabitto et al. (2024) Nat Neurosci,de104f7e-14fa-4795-bd19-b5ee2c1563e0,80c8b3f5-5a4c-4365-bb41-b5915e400d73,L6 IT - MTG: Seattle Alzheimer's Disease Atlas...,de104f7e-14fa-4795-bd19-b5ee2c1563e0.h5ad,45252
1568,1568,Publication: https://doi.org/10.1038/s41593-02...,1ca90a2d-2943-483d-b678-b809bf464c30,SEA-AD: Seattle Alzheimer’s Disease Brain Cell...,10.1038/s41593-024-01774-5,Gabitto et al. (2024) Nat Neurosci,0ed60482-a34f-4268-b576-d69cc30210f6,fd5e1f2f-0314-465e-993f-ef98f29ce52c,Lamp5 - DLPFC: Seattle Alzheimer's Disease Atl...,0ed60482-a34f-4268-b576-d69cc30210f6.h5ad,55968
1596,1596,Publication: https://doi.org/10.1038/s41593-02...,1ca90a2d-2943-483d-b678-b809bf464c30,SEA-AD: Seattle Alzheimer’s Disease Brain Cell...,10.1038/s41593-024-01774-5,Gabitto et al. (2024) Nat Neurosci,74d584f0-74fc-482e-b944-e76f29c1ab85,358abb79-36a5-4a26-acca-7d2bf20631ff,Astrocyte - DLPFC: Seattle Alzheimer's Disease...,74d584f0-74fc-482e-b944-e76f29c1ab85.h5ad,87444
1606,1606,Publication: https://doi.org/10.1038/s41593-02...,1ca90a2d-2943-483d-b678-b809bf464c30,SEA-AD: Seattle Alzheimer’s Disease Brain Cell...,10.1038/s41593-024-01774-5,Gabitto et al. (2024) Nat Neurosci,03181d87-4769-41e7-8c39-d9a81835f0d2,75b2c9e3-347c-4759-b9c2-ed2ad3bd98d3,Sst - DLPFC: Seattle Alzheimer's Disease Atlas...,03181d87-4769-41e7-8c39-d9a81835f0d2.h5ad,75706
1608,1608,Publication: https://doi.org/10.1038/s41593-02...,1ca90a2d-2943-483d-b678-b809bf464c30,SEA-AD: Seattle Alzheimer’s Disease Brain Cell...,10.1038/s41593-024-01774-5,Gabitto et al. (2024) Nat Neurosci,d87f3f91-dca4-494b-8993-c4e3008a8fa5,057d399c-a4a3-4338-abde-821ac996069f,Pvalb - MTG: Seattle Alzheimer's Disease Atlas...,d87f3f91-dca4-494b-8993-c4e3008a8fa5.h5ad,90804
1609,1609,Publication: https://doi.org/10.1038/s41593-02...,1ca90a2d-2943-483d-b678-b809bf464c30,SEA-AD: Seattle Alzheimer’s Disease Brain Cell...,10.1038/s41593-024-01774-5,Gabitto et al. (2024) Nat Neurosci,a0d173dd-bb10-4d13-8b9a-e13a4ee83c8c,0278d441-2d25-41aa-bf74-0710d8756631,Vip - MTG: Seattle Alzheimer's Disease Atlas (...,a0d173dd-bb10-4d13-8b9a-e13a4ee83c8c.h5ad,104514
1632,1632,Publication: https://doi.org/10.1038/s41593-02...,1ca90a2d-2943-483d-b678-b809bf464c30,SEA-AD: Seattle Alzheimer’s Disease Brain Cell...,10.1038/s41593-024-01774-5,Gabitto et al. (2024) Nat Neurosci,6437bc9c-16cb-46c8-8f79-9a7384a0212a,4abebec9-65d7-488a-a140-0b0c0bd68244,L6 IT - DLPFC: Seattle Alzheimer's Disease Atl...,6437bc9c-16cb-46c8-8f79-9a7384a0212a.h5ad,47373
1634,1634,Publication: https://doi.org/10.1038/s41593-02...,1ca90a2d-2943-483d-b678-b809bf464c30,SEA-AD: Seattle Alzheimer’s Disease Brain Cell...,10.1038/s41593-024-01774-5,Gabitto et al. (2024) Nat Neurosci,9940f951-3dc0-4579-bbb2-2392786e59a3,ee76ede3-5006-4caa-a960-4df0b462f88b,Oligodendrocyte - DLPFC: Seattle Alzheimer's D...,9940f951-3dc0-4579-bbb2-2392786e59a3.h5ad,145995
1688,1688,Publication: https://doi.org/10.1038/s41593-02...,1ca90a2d-2943-483d-b678-b809bf464c30,SEA-AD: Seattle Alzheimer’s Disease Brain Cell...,10.1038/s41593-024-01774-5,Gabitto et al. (2024) Nat Neurosci,53bc5729-6202-4351-bc99-1f36139e9dc4,34664d7f-0efc-4182-a4e4-66586ab244a9,Vip - DLPFC: Seattle Alzheimer's Disease Atlas...,53bc5729-6202-4351-bc99-1f36139e9dc4.h5ad,100215
1702,1702,Publication: https://doi.org/10.1038/s41593-02...,1ca90a2d-2943-483d-b678-b809bf464c30,SEA-AD: Seattle Alzheimer’s Disease Brain Cell...,10.1038/s41593-024-01774-5,Gabitto et al. (2024) Nat Neurosci,9ff9f9ba-016b-4cbb-8899-45dc20860b8b,e63ddede-504b-480f-90c8-c281b50f1801,L4 IT - DLPFC: Seattle Alzheimer's Disease Atl...,9ff9f9ba-016b-4cbb-8899-45dc20860b8b.h5ad,81869
1723,1723,Publication: https://doi.org/10.1038/s41593-02...,1ca90a2d-2943-483d-b678-b809bf464c30,SEA-AD: Seattle Alzheimer’s Disease Brain Cell...,10.1038/s41593-024-01774-5,Gabitto et al. (2024) Nat Neurosci,605b89b1-c474-4180-8c0b-88afb5920991,f877428d-86e4-470d-8edc-7df284d32e02,L5 IT - MTG: Seattle Alzheimer's Disease Atlas...,605b89b1-c474-4180-8c0b-88afb5920991.h5ad,128090
1731,1731,Publication: https://doi.org/10.1038/s41593-02...,1ca90a2d-2943-483d-b678-b809bf464c30,SEA-AD: Seattle Alzheimer’s Disease Brain Cell...,10.1038/s41593-024-01774-5,Gabitto et al. (2024) Nat Neurosci,04c94a7d-1133-42c9-bb48-c697bd302a8d,4dc1db43-697c-47ad-92ca-d3f8227b662d,Pvalb - DLPFC: Seattle Alzheimer's Disease Atl...,04c94a7d-1133-42c9-bb48-c697bd302a8d.h5ad,116142
1734,1734,Publication: https://doi.org/10.1038/s41593-02...,1ca90a2d-2943-483d-b678-b809bf464c30,SEA-AD: Seattle Alzheimer’s Disease Brain Cell...,10.1038/s41593-024-01774-5,Gabitto et al. (2024) Nat Neurosci,ac0fee7e-0999-4319-b244-20278e1ff2fb,43919138-a503-4a8b-a013-7fc0b6d11fbd,L4 IT - MTG: Seattle Alzheimer's Disease Atlas...,ac0fee7e-0999-4319-b244-20278e1ff2fb.h5ad,168860
1744,1744,Publication: https://doi.org/10.1038/s41593-02...,1ca90a2d-2943-483d-b678-b809bf464c30,SEA-AD: Seattle Alzheimer’s Disease Brain Cell...,10.1038/s41593-024-01774-5,Gabitto et al. (2024) Nat Neurosci,44c83972-e5d2-4858-ac58-2df9f4bf564b,b5db33b8-0a69-4f3c-800c-938fae20f7ae,L5 IT - DLPFC: Seattle Alzheimer's Disease Atl...,44c83972-e5d2-4858-ac58-2df9f4bf564b.h5ad,104106
1801,1801,Publication: https://doi.org/10.1038/s41593-02...,1ca90a2d-2943-483d-b678-b809bf464c30,SEA-AD: Seattle Alzheimer’s Disease Brain Cell...,10.1038/s41593-024-01774-5,Gabitto et al. (2024) Nat Neurosci,b74100ea-1a1a-486a-9cad-70ae44150935,591f2ed3-d2de-4d0e-b820-78347ce67960,L2/3 IT - MTG: Seattle Alzheimer's Disease Atl...,b74100ea-1a1a-486a-9cad-70ae44150935.h5ad,330085
1820,1820,Publication: https://doi.org/10.1038/s41593-02...,1ca90a2d-2943-483d-b678-b809bf464c30,SEA-AD: Seattle Alzheimer’s Disease Brain Cell...,10.1038/s41593-024-01774-5,Gabitto et al. (2024) Nat Neurosci,646e3e87-e46b-4b12-85b5-8d8589e26088,b499a696-c78d-45c0-a1a9-c35e4d28970d,L2/3 IT - DLPFC: Seattle Alzheimer's Disease A...,646e3e87-e46b-4b12-85b5-8d8589e26088.h5ad,341960
1844,1844,Publication: https://doi.org/10.1038/s41593-02...,1ca90a2d-2943-483d-b678-b809bf464c30,SEA-AD: Seattle Alzheimer’s Disease Brain Cell...,10.1038/s41593-024-01774-5,Gabitto et al. (2024) Nat Neurosci,c2876b1b-06d8-4d96-a56b-5304f815b99a,92b37feb-aa2c-40d7-bd90-0a9b5ddb3b27,Whole Taxonomy - MTG: Seattle Alzheimer's Dise...,c2876b1b-06d8-4d96-a56b-5304f815b99a.h5ad,1378211
1845,1845,Publication: https://doi.org/10.1038/s41593-02...,1ca90a2d-2943-483d-b678-b809bf464c30,SEA-AD: Seattle Alzheimer’s Disease Brain Cell...,10.1038/s41593-024-01774-5,Gabitto et al. (2024) Nat Neurosci,6f7fd0f1-a2ed-4ff1-80d3-33dde731cbc3,dad4819b-4c14-439c-b32a-2c8d68bd22e1,Whole Taxonomy - DLPFC: Seattle Alzheimer's Di...,6f7fd0f1-a2ed-4ff1-80d3-33dde731cbc3.h5ad,1395601

In [31]:
df[df.dataset_id == "e4ddac12-f48f-4455-8e8d-c2a48a683437"]

,soma_joinid,citation,collection_id,collection_name,collection_doi,collection_doi_label,dataset_id,dataset_version_id,dataset_title,dataset_h5ad_path,dataset_total_cell_count
1642,1642,Publication: https://doi.org/10.1126/science.a...,d17249d2-0e6e-4500-abb8-e6c93fa1ac6f,Transcriptomic cytoarchitecture reveals princi...,10.1126/science.adf6812,Jorstad et al. (2023) Science,e4ddac12-f48f-4455-8e8d-c2a48a683437,cb095b8e-acc5-4aa1-b3e8-eebdca374cb7,Supercluster: CGE-derived interneurons,e4ddac12-f48f-4455-8e8d-c2a48a683437.h5ad,129495

In [32]:
count = df[df["dataset_id"] == "c2876b1b-06d8-4d96-a56b-5304f815b99a"]["dataset_total_cell_count"]
count = count.iloc[0]
count

np.int64(1378211)

In [6]:
print(latest_census.uri)
latest_version = latest_census.uri.split("/")[4]
print("Resolved census version:", latest_version)

s3://cellxgene-census-public-us-west-2/cell-census/2025-11-10/soma/
Resolved census version: 2025-11-10

## get  human datasets in latest release that have cells is_primary_data == True

In [4]:
latest_human_obs_has_primary_data = cellxgene_census.get_obs(
    latest_census, 
    "homo_sapiens", 
    value_filter = f"is_primary_data == True",
    column_names = ["dataset_id"]
)

In [5]:
latest_datasets_has_primary_data = latest_human_obs_has_primary_data["dataset_id"].unique()

In [6]:
len(latest_datasets_has_primary_data), len(latest_human_obs_has_primary_data)

(568, 97980316)

In [8]:
latest_datasets_has_primary_data

['a5d95a42-0137-496f-8a60-101e17f263c8', 'd3566d6a-a455-4a15-980f-45eb29114cab', 'e347396c-a7ff-4691-9f7a-99a43555ca18', 'eec804b9-2ae5-44f0-a1b5-d721e21257de', '0c9a8cfb-6649-4d52-b418-6d8e56bd7afe', ..., '37a17b78-4864-4a42-b67b-31c00962795a', 'd6505c89-c43d-4c28-8c4f-7351a5fd5528', '53d208b0-2cfd-4366-9866-c3c6114081bc', 'c2876b1b-06d8-4d96-a56b-5304f815b99a', '6f7fd0f1-a2ed-4ff1-80d3-33dde731cbc3']
Length: 566
Categories (1087, object): ['0041b9c3-6a49-4bf7-8514-9bc7190067a7', '00476f9f-ebc1-4b72-b541-32f912ce36ea', '00593d17-0693-4646-acad-89dbefba11bb', '0087cde2-967d-4f7c-8e6e-40e4c9ad1891', ..., 'ff45e623-7f5f-46e3-b47d-56be0341f66b', 'ff4cfa86-9c0c-4b7c-abd6-90547657d04f', 'ff7d15fa-f4b6-4a0e-992e-fd0c9d088ded', 'ff995299-bf56-4d11-914d-b77949f02fb1']

In [9]:
# Grab dataset-level metadata from human obs
obs_df = cellxgene_census.get_obs(
    latest_census, 
    organism="homo_sapiens", 
    column_names=["dataset_id", "is_primary_data"]
)

In [10]:
obs_df.shape

(159029419, 2)

In [21]:
print(obs_df.drop_duplicates().value_counts())

dataset_id                            is_primary_data
0041b9c3-6a49-4bf7-8514-9bc7190067a7  False              1
b617ee1b-f8c8-4de9-b82b-e803ab93550d  False              1
adda0684-f8ea-4403-b393-2a25607077c4  True               1
ae29ebd0-1973-40a4-a6af-d15a5f77a80f  False              1
ae45e70d-cae7-45f5-8ee8-6655f208273c  False              1
                                                        ..
55cf0ea3-9d2b-4294-871e-bb4b49a79fc7  False              1
569bce19-14c3-436f-bebf-543e5ea025dc  False              1
56c33a38-2732-4e53-a9c1-1bc61eda9a99  False              1
56c4912d-2bae-4b64-98f2-af8a84389208  False              1
ff995299-bf56-4d11-914d-b77949f02fb1  False              1
Name: count, Length: 969, dtype: int64

In [22]:
# Group by dataset_id and check unique flags
dataset_flags = obs_df.groupby("dataset_id")["is_primary_data"].unique()

# Filter those that have both True and False
mixed_datasets = dataset_flags[dataset_flags.apply(lambda x: set(x) == {True, False})]
print(mixed_datasets)

/tmp/ipykernel_2697/146002157.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  dataset_flags = obs_df.groupby("dataset_id")["is_primary_data"].unique()

dataset_id
02792605-4760-4023-82ad-40fc4458a5db    [True, False]
0436a180-cb44-47ba-8ffa-807b7a468469    [False, True]
07760522-707a-4a1c-8891-dbd1226d6b27    [False, True]
0b75c598-0893-4216-afe8-5414cab7739d    [False, True]
0c9a8cfb-6649-4d52-b418-6d8e56bd7afe    [True, False]
                                            ...
e7c5ba7e-4be0-4696-af50-a07d0dc7aac5    [False, True]
eb499fd8-7000-419f-8854-926b9b61b11f    [True, False]
f5be4b96-f5a3-4c3d-84ac-6f69daf744d5    [False, True]
f8d8b443-bca6-4c3c-9042-669dfb7f8030    [False, True]
fd072bc3-2dfb-46f8-b4e3-467cb3223182    [True, False]
Name: is_primary_data, Length: 69, dtype: object

In [23]:
"8e10f1c4-8e98-41e5-b65f-8cd89a887122" in mixed_datasets

False

## latest_census_datasets

In [9]:
latest_census_datasets = latest_census["census_info"]["datasets"].read().concat().to_pandas()

## get dataset ids and info from our current db

In [27]:
already_have_dataset_list =[]

if embedding=="UCE":
    local_dir = "UCE_npy_obs"
    suffix = "_uce.npy"
elif embedding=="scimilarity":
    local_dir = "SCimilarity_npy_obs"
    suffix = "_scimilarity.npy"
for root, dirs, files in os.walk(local_dir):
    for file in files:
        if file.startswith("ucsc-"):
            continue
        if file.endswith(suffix):
            dataset_id = file.removesuffix("_uce.npy")
            match = re.match(r'^([a-f0-9\-]+)_', file)
            real_dataset_id = match.group(1)
            if real_dataset_id not in already_have_dataset_list:
                already_have_dataset_list.append(real_dataset_id)
len(already_have_dataset_list)

508

In [28]:
df = latest_census_datasets[latest_census_datasets["dataset_id"].isin(already_have_dataset_list)]
df = df[["dataset_id", "dataset_total_cell_count", "collection_name", "dataset_title", "collection_doi_label","collection_doi"]].sort_values(by="dataset_total_cell_count", ascending=True)
df

,dataset_id,dataset_total_cell_count,collection_name,dataset_title,collection_doi_label,collection_doi
288,149b2c3f-ee11-47a7-984b-923570280bd7,301,HVS: Human variation study,SstChodl - neocortex: Human variation study (HVS),Johansen et al. (2023) Science,10.1126/science.adf2359
441,5e7fff82-b8eb-4220-bf65-c6feb6765ea1,563,HVS: Human variation study,L5ET - neocortex: Human variation study (HVS),Johansen et al. (2023) Science,10.1126/science.adf2359
398,4859642c-d155-437b-adf5-83ca6c1bef67,582,HVS: Human variation study,Endo - neocortex: Human variation study (HVS),Johansen et al. (2023) Science,10.1126/science.adf2359
417,f9cfac8d-bff6-47a2-a1f6-503827d375f5,637,HVS: Human variation study,VLMC - neocortex: Human variation study (HVS),Johansen et al. (2023) Science,10.1126/science.adf2359
193,61d327d1-2227-4c5f-9367-e3559dc79b07,796,Characterizing smoking-induced transcriptional...,Characterizing smoking-induced transcriptional...,Duclos et al. (2019) Sci. Adv.,10.1126/sciadv.aaw3413
...,...,...,...,...,...,...
1814,13149914-ea03-4f01-8bf6-b793b667127b,1665937,Comprehensive cell atlas of the first-trimeste...,All,Braun et al. (2023) Science,10.1126/science.adf1226
1834,d7f5d8d0-6150-48d7-b094-c34286ad11a1,1920454,An integrated transcriptomic cell atlas of hum...,HNOCA Extended: The Human Neural Organoid Atlas,He et al. (2024) Nature,10.1038/s41586-024-08172-8
1837,9f222629-9e39-47d0-b83f-e08d610c7479,2282447,The integrated Human Lung Cell Atlas,An integrated cell atlas of the human lung in ...,Sikkema et al. (2023) Nat Med,10.1038/s41591-023-02327-2
1840,8e10f1c4-8e98-41e5-b65f-8cd89a887122,2480956,Human Brain Cell Atlas v1.0,All neurons,Siletti et al. (2023) Science,10.1126/science.add7046
1833,f7c1c579-2dc0-47e2-ba19-8165c5a0e353,4062980,A human cell atlas of fetal gene expression,Survey of human embryonic development,Cao et al. (2020) Science,10.1126/science.aba7721

In [30]:
import datetime
today = datetime.date.today()

output = f"datasets.info.cxg.{embedding}.{today}.txt"
with open(output, "w") as f:
    df.to_csv(f, sep="\t", index=False)

### new data from latest cellxgene_census

In [12]:
current_datasets = already_have_dataset_list
difference = [x for x in latest_datasets_has_primary_data if x not in current_datasets]
len(difference)

564

In [13]:
difference

['a5d95a42-0137-496f-8a60-101e17f263c8',
 'd3566d6a-a455-4a15-980f-45eb29114cab',
 'e347396c-a7ff-4691-9f7a-99a43555ca18',
 'eec804b9-2ae5-44f0-a1b5-d721e21257de',
 '0c9a8cfb-6649-4d52-b418-6d8e56bd7afe',
 '4993d61c-1d04-4630-9c61-8d9431f39adc',
 'b25f3834-69b3-4d87-a272-3938432d1f30',
 '2f6a20f1-173d-4b8d-860b-c47ffea120fa',
 'a65bcc2d-4243-44c1-a262-ab7dcddfcf86',
 '6fc37633-13f5-4bf0-af95-52808143bffd',
 '61d327d1-2227-4c5f-9367-e3559dc79b07',
 'e5f5d954-cf0e-4bd8-9346-8d1ddf15a08b',
 '62de80d7-e6c4-4ff0-ad4c-d3d36f57cb93',
 '7d98cc44-b090-4dc8-804f-2750c84fe9d7',
 'd973ea15-3722-4bc8-a0e8-1d956d26e203',
 'b3a5a10f-b1cb-4e8e-abce-bf345448625b',
 '8a554710-08bc-4005-87cd-da9675bdc2e7',
 '66d15835-5dc8-4e96-b0eb-f48971cb65e8',
 'dbf0bd35-87f8-4b25-bc90-a3c54f379907',
 'ce009dc1-ac57-4386-b72f-5c575701c253',
 '731e6380-879f-4b0b-9a1f-2150208852ef',
 'ea786a06-5855-48b7-80d7-0313a21a2044',
 '149b2c3f-ee11-47a7-984b-923570280bd7',
 '774c18c5-efa1-4dc5-9e5e-2c824bab2e34',
 '601c7454-17ff-432c-8e0d-902bfddb8013',
 'ee195b7d-184d-4dfa-9b1c-51a7e601ac11',
 'd2bc2703-a9b5-4949-b85d-61da7b9961b1',
 '470565f2-5afc-456a-b617-18e4496c04fd',
 '4c6f9f26-5470-455b-8933-c408232fbf56',
 'dc30c3ec-46d6-4cd8-8ec1-b544a3d0f503',
 '51f476f7-b24d-42f3-8871-7dab3fa35e96',
 '6e00ccf7-0749-46ef-a999-dba785630d52',
 'cab0bc48-744c-461b-aaf4-7bf2cb7af00d',
 '50eb1e23-b8d4-4f76-a184-44e5541fa05a',
 'af8b241a-c72c-4470-b1a4-80e7336c6ab6',
 '4859642c-d155-437b-adf5-83ca6c1bef67',
 'b07e5164-baf6-43d2-bdba-5a249d0da879',
 'f6d9f2ad-5ec7-4d53-b7f0-ceb0e7bcd181',
 '01c93cf6-b695-4e30-a26e-121ae8b16a9e',
 '73b7d0aa-035f-4a15-9f1d-f56b70204591',
 '856c1b98-5727-49da-bf0f-151bdb8cb056',
 '84230ea4-998d-4aa8-8456-81dd54ce23af',
 'f9cfac8d-bff6-47a2-a1f6-503827d375f5',
 '79ef1959-a6b4-4cac-82ca-30feaec48df1',
 'c874f155-9bf9-4928-b821-f52c876b3e48',
 'f801b7a9-80a6-4d09-9161-71474deb58ae',
 '7b75b2c4-6d99-40be-9a61-391455d859e6',
 '80d7111d-f9fe-49fd-871e-6e618312c341',
 'cd4c96bb-ad66-4e83-ba9e-a7df8790eb12',
 'a9bedd04-51cb-42ad-83fe-cd749de71f1b',
 '5e7fff82-b8eb-4220-bf65-c6feb6765ea1',
 'ed9e9f96-4f08-49d2-bef5-b2c29adf3edc',
 '4e74d843-8d7a-497a-918a-f079ef141b6d',
 '248cf7bf-508b-4c28-a2fd-cabe2ab956aa',
 '2f7230e7-4706-4924-b571-473fc1e52c30',
 '881fe679-c6e0-45a3-9427-c4e81be6921f',
 'd3d4baff-d142-4f13-acc6-96a4ef6a3e95',
 '0ee5ae70-c3f5-473f-bd1c-287f4690ffc5',
 'f3ee7613-b27f-4deb-a5aa-1d4f9a2db963',
 'ea01c125-67a7-4bd3-a8b0-e1b53a011b7e',
 '3e55180c-780a-4424-9434-5296640ffc0d',
 'f156606a-dd9a-49fd-bc40-0e069b6cf07c',
 '4ce8d8ec-b94c-4b79-afcb-b094336d8a78',
 'a5b5d1f3-dd8b-44f6-a685-15f0f741c062',
 'bd3e3487-c1e6-4298-b9de-8bdcf3f938d7',
 '95d3b0fb-b8a7-4bec-a2e8-cded3222ff07',
 '4a90bbba-df97-4a28-83ae-7386fe7d9167',
 '492d9f77-c4c8-485d-92d7-7686fe6c8482',
 '76af615b-12fe-4ebb-b8c6-239ad29e26e3',
 '2a65bd41-4a3f-42f4-98b2-c53962811152',
 '06ef6b36-6c9b-4e10-8a94-d0baf274276e',
 '14363b6e-3428-45b0-8704-10fd5d6316df',
 'bdd109f1-ca27-45dc-bb9f-473008449428',
 'b550fd94-97e0-42e2-90f7-7434781ea2f8',
 'a1b9c51e-a408-4f7f-bccb-abefe20ae2a5',
 'f5be4b96-f5a3-4c3d-84ac-6f69daf744d5',
 '8039c63d-08b0-4fc9-af0f-5b57f08ca0da',
 '124744b8-4681-474a-9894-683896122708',
 '1f1c5c14-5949-4c81-b28e-b272e271b672',
 '4dd1cd23-fc4d-4fd1-9709-602540f3ca6f',
 'ed11cc3e-2947-407c-883c-c53b043917c3',
 '5b25a46f-f1cf-4caa-9e10-6ab81dfe9174',
 'd5452b83-7c3d-4d7c-ab7a-c7fece7196c5',
 '4b83f213-b96b-4c87-a884-9b81faddb194',
 '07dd8c34-4625-480a-8ee4-273a06c3082b',
 'c05fb583-eb2f-4e3a-8e74-f9bd6414e418',
 '42b6a476-c51d-4f8b-b68b-44941b3a11bf',
 '5cdbb2ea-c622-466d-9ead-7884ad8cb99f',
 'db59611b-42de-4035-93aa-1ed39f38b467',
 'c5cfa2b7-abb1-4a50-908f-707b54ca606b',
 '2727d83a-0af0-443a-bff8-58dc7028289a',
 '364348b4-bc34-4fe1-a851-60d99e36cafa',
 '8d73847b-33e7-48f0-837f-e3e6579bf12d',
 'eeacb0c1-2217-4cf6-b8ce-1f0fedf1b569',
 '1a018108-b4b6-457b-ba15-046d5e98c169',
 '43560d7c-acd6-4ede-830d-c9ffc6cd0862',
 '77044335-0ac5-4406-9b3f-8cdd3656d67b',
 'adda0684-f8ea-4403-b393-2a25607077c4',
 '8fcf0ccc-67b2-43a3-90be-075f85169bef',
 '78f40dd6-ed22-470d-8547-6fb5746c25da',
 '00476f9f-ebc1-4b72-b541-32f912ce36ea',
 '8623d55f-d91c-41c2-ae68-ed2072fd268d',
 'ca20e2ac-5676-4158-b5d0-0c2b15898b19',
 'f3c49918-4707-4d92-bb6d-2b5b4eb9d1b4',
 'de94c504-4b58-4f42-b68d-74a8e4892f0e',
 'fbf173f9-f809-4d84-9b65-ae205d35b523',
 '6a270451-b4d9-43e0-aa89-e33aac1ac74b',
 'd7d7e89c-c93a-422d-8958-9b4a90b69558',
 'bc7260e0-54cf-4b0b-823d-93f5b850f757',
 '3241c34f-581a-4de3-81fe-28e3de182680',
 '30f5e171-83d7-4fc0-bf75-384f122346b3',
 'fbdd8c17-b34a-4cbc-abc4-1aeaa294a538',
 '090da8ea-46e8-40df-bffc-1f78e1538d27',
 '82f6af6d-5313-439a-9936-5e844be49a70',
 'f15e263b-6544-46cb-a46e-e33ab7ce8347',
 '9df60c57-fdf3-4e93-828e-fe9303f20438',
 'a59ba9fa-1407-4f15-8c56-d3637421570d',
 '03d38670-1444-4001-bc53-9936e61d9b20',
 '343ff97c-85df-494b-8400-beb937618611',
 '6929d6d1-6f81-44d7-bd35-5a580259af81',
 '7970bd6b-f752-47a9-8643-2af16855ec49',
 'b796f27e-e191-4f2d-b40c-e6ac58163b4e',
 '22658f4f-9268-41ad-8828-cc53f4baa9fa',
 '8dc29642-be06-46dc-a289-8075915745d4',
 '2a8ca8f3-5599-4cda-b973-3a2dfc3c1fe6',
 'be884a28-0eac-4eca-9c23-1294a93cf56e',
 '781cc817-3fd0-487c-a55a-b47b2786a05d',
 '489318a0-24c3-4f5c-b105-f084ed0ea026',
 '9bfecd44-e6b5-4072-9b64-cb7f0a117f88',
 'a24ce10f-5a87-4e1f-a34a-f4fe5fc84052',
 'f8d8b443-bca6-4c3c-9042-669dfb7f8030',
 'e04daea4-4412-45b5-989e-76a9be070a89',
 '381aa407-317a-40ef-8048-7ce0eacc4266',
 'd5c67a4e-a8d9-456d-a273-fa01adb1b308',
 '6cf3634d-e911-44ad-bf52-c747a9af3c01',
 '40569510-2282-461b-84df-6218ef208e0e',
 '9ea768a2-87ab-46b6-a73d-c4e915f25af3',
 '8dc858b0-b076-4326-94bb-7c2d1cd721a3',
 'b8681124-aabf-4904-b9c9-66d834bf5bba',
 '35c8a04c-8639-4d15-8228-765d8d93fc96',
 '2dd9d7a2-4bee-4c3f-a1f5-89bc3271c4f0',
 '68b6114f-e990-4033-bfb3-c35536633aaa',
 '07b1d7c8-5c2e-42f7-9246-26f746cd6013',
 '55ca4411-8c7d-4aef-a572-50852e030c05',
 'e22482ee-19e8-40bc-9f6e-541dc3c82c20',
 '460dfe21-0550-4521-92fe-db0f3036d8b0',
 'f20f44ef-a0d4-4d94-87de-037fd47141f0',
 '8e47ed12-c658-4252-b126-381df8d52a3d',
 '64767efb-49b0-4562-a1bd-e619a5d9db41',
 '456e8b9b-f872-488b-871d-94534090a865',
 'cfa3c355-ee77-4fc8-9a00-78e61d23024c',
 '4dd00779-7f73-4f50-89bb-e2d3c6b71b18',
 '86282760-5099-4c71-8cdd-412dcbbbd0b9',
 'c4dd26a8-d956-4bee-a233-44b573f2ce27',
 '9813a1d4-d107-459e-9b2e-7687be935f69',
 'be39785b-67cb-4177-be19-a40ee3747e45',
 '07760522-707a-4a1c-8891-dbd1226d6b27',
 'f9034091-2e8f-4ac6-9874-e7b7eb566824',
 'f3565fda-499a-4d20-bd92-563c09954c42',
 '6c600df6-ddca-4628-a8bb-1d6de1e3f9b4',
 '39ed7d98-676d-4b8d-9d0a-0f3b60914ead',
 'bac09168-940b-4b11-8d55-b4955f80b98d',
 'd7cff847-6403-44a6-ad8a-2f5a783639dd',
 '7cd3c321-e487-4b51-a8af-9bf671b59fe5',
 'babbf9f3-f482-45a5-ba76-c41f4c2f503e',
 'd1207c81-7309-43a7-a5a0-f4283670b62b',
 'c7856243-c59a-4b70-8ce7-25b94c2d9da1',
 '4b6af54a-4a21-46e0-bc8d-673c0561a836',
 '867757c1-3b1a-49d9-a0cd-17767eb160cc',
 '44882825-0da1-4547-b721-2c6105d4a9d1',
 'd18736c3-6292-4379-919a-d6d973204c87',
 '0f4865d5-8000-4f68-8ac7-f5efea9e5e70',
 'f5be9ed2-5d41-4a52-91e4-4ff24ff84900',
 '13b61a7d-5605-4948-ba48-02c588960143',
 'a7b4f565-691d-43ea-bf4a-d2d1d52bb4b4',
 'f7ca7eb9-0919-4eba-99a1-21ba382b4174',
 '51d9716c-50bb-4fd8-8d1e-7d9329969cb7',
 'de2c780c-1747-40bd-9ccf-9588ec186cee',
 '2872f4b0-b171-46e2-abc6-befcf6de6306',
 'a84face4-eb30-4f43-994f-c6a13a097808',
 '43a1506b-aa9e-46a3-b288-d210f4595ddf',
 '27d3952f-fbbc-497d-98d1-f37f3d555235',
 '12c3efd8-d515-42e6-b93c-4961e599d524',
 'ccfdcad0-7104-46b9-addf-fd66a2a15907',
 'a4116666-d295-4443-a174-0acc283f92c4',
 '8b2e5453-faf7-46ea-9073-aea69b283cb7',
 '4d43082e-59cd-43ac-b77d-54d55519c881',
 'd319af7f-be2e-441e-8caa-3b8a88480e89',
 '09b518f9-da64-44cc-aec8-70a89d55611f',
 '87a06a2a-16c6-42f7-af1b-529fad431051',
 '2856d06c-0ff9-4e01-bfc9-202b74d0b60f',
 '5a73f63f-18a2-49b5-b431-2c469c41a41b',
 'b6e502d7-0d07-408e-a291-91b63af0a40a',
 '9372df2d-13d6-4fac-980b-919a5b7eb483',
 'acd544d0-4d8b-46c7-98b3-fc48f7e6fdb7',
 '01209dce-3575-4bed-b1df-129f57fbc031',
 '095940cb-7422-4510-96e2-cbafd961eb88',
 '93131426-0124-4ab4-a013-9dfbcd99d467',
 'd6a5b240-cc8f-45c1-ad36-2fc291e15e8e',
 '595c9010-99ec-462d-b6a1-2b2fe5407871',
 '6ceeaa86-9ceb-4582-b390-6d4dd6ff0572',
 'd7dcfd8f-2ee7-4385-b9ac-e074c23ed190',
 '1e5bd3b8-6a0e-4959-8d69-cafed30fe814',
 '3de0ad6d-4378-4f62-b37b-ec0b75a50d94',
 '7d3ab174-e433-40fc-a352-6fe71b1a19f9',
 '2f132ec9-24b5-422f-9be0-ccef03b4fe28',
 '4724c395-0c46-46d2-81f7-60fd271fb488',
 '5e5ab909-f73f-4b57-98a0-6d2c5662f6a4',
 '3a702020-cf66-4ef5-9d11-4a5e835b7efb',
 '8e5978bd-0e48-4a09-a92d-fa2985059f05',
 'dd03ce70-3243-4c96-9561-330cc461e4d7',
 'ff7d15fa-f4b6-4a0e-992e-fd0c9d088ded',
 '79884ae5-e026-4d4a-858f-e807960bd4f7',
 'de985818-285f-4f59-9dbd-d74968fddba3',
 '19e46756-9100-4e01-8b0e-23b557558a4c',
 '367b55f4-d543-49aa-90e8-4765fcb8c687',
 '182f6a56-7360-4924-a74e-1772e07b3031',
 '390b376d-8857-4b4b-991f-0d7326938172',
 'fa554686-fc07-44dd-b2de-b726d82d26ec',
 'e5b1115b-a486-49bb-bda3-8261822836e0',
 '64f4ad90-a422-400a-944d-4ce0f39594a7',
 '1cf24082-59de-4029-ac81-6e398768af3a',
 'f512b8b6-369d-4a85-a695-116e0806857f',
 'db1d2c1b-2ee1-45d5-9d53-69a327cd77e6',
 '821a8e3e-87ec-41ee-bd69-cd4377057d38',
 'f8dda921-5fb4-4c94-a654-c6fc346bfd6d',
 '72822932-10f6-466f-baf3-a2c1d89364bc',
 '78c62d4e-abf1-405b-bb51-368720814529',
 'e3cc5b85-62ec-4add-bee3-73c8fd11e59d',
 '9ec34295-ab16-47e2-af33-b884143e520b',
 'ed33c203-233a-476a-a56b-28da945fdd32',
 'fa8605cf-f27e-44af-ac2a-476bee4410d3',
 '70e4f35b-c98c-45a1-9aa9-2053b07315dd',
 '53ce2631-3646-4172-bbd9-38b0a44d8214',
 '88a01d4a-5197-45be-b5ae-e019aef43376',
 '7e7f63c5-d964-40be-83de-ecbcccafd233',
 '3e524d45-2265-4440-b903-3c30d51a0b17',
 '19b21f40-db42-4a71-a0d6-913e83b17784',
 '5bc23cb2-8cfc-4960-bab1-c3027fbeefc4',
 'fe1a73ab-a203-45fd-84e9-0f7fd19efcbd',
 'e067e5ca-e53e-485f-aa8e-efd5435229c8',
 '1b767f95-d0a0-4a3d-b394-cc665d86c3dc',
 '1196334f-a441-474a-95ee-400780941690',
 '3f56901c-dd4a-47d6-b60b-7b0c0111cfb2',
 'e8681d74-ac9e-4be5-be14-1cf1bbd54dd7',
 'f502c312-05dc-4fd4-a762-92a63e92b539',
 '18500fcd-9960-49cb-8a8e-7d868dc14efe',
 '52f18bc3-52d9-487b-bf8f-f0b7aa684b09',
 '322c816f-608a-4da1-99c4-36ca4ad45146',
 '7c1c3d47-3166-43e5-9a95-65ceb2d45f78',
 '2672b679-8048-4f5e-9786-f1b196ccfd08',
 'e500acbf-f166-4c46-b290-f93506cf26d3',
 '61af564d-e5ea-4d34-a0f3-2668a00db376',
 '900fdf13-150d-4695-9f8c-4c09105ba2eb',
 '5500c673-1610-40a0-86d9-64d987ae50e6',
 '4593c820-512d-4805-a10f-c0b864a7cc8c',
 '4976b234-9028-4b4b-8a2f-8ac59d636219',
 'e2a325e2-5633-4950-ae46-ebff70979e3b',
 'd582f63a-3c88-4e38-8cd3-8682dbe40f64',
 '40318d39-3d8f-49f4-8455-a2e1365c5c5b',
 '715327a6-7978-4896-ba91-69d6b04dbbfb',
 'c05e6940-729c-47bd-a2a6-6ce3730c4919',
 '644a578d-ffdc-446b-9679-e7ab4c919c13',
 'acae7679-d077-461c-b857-ee6ccfeb267f',
 'df1edb87-e512-43ae-b5f4-cb179cfc2bb4',
 '234c23d0-d6cd-4612-a40d-e5811727564b',
 '43b7e156-65b3-4a7b-8c7a-08528e4b21d0',
 'b6ee0939-b5b9-4e03-9d69-96fb6bf5d434',
 '639ffc23-14db-4060-9027-3c90314200f8',
 '5d3fc988-765d-48ba-bfb5-151ef2988cac',
 'f5a04dff-d394-4023-8811-65494e8bb11d',
 '9a64bf99-ebe5-4276-93a8-bee9dff1cd47',
 '3f31f8ce-bbf6-4df8-8203-aa240ed03026',
 '1185a7d3-a9c1-4280-9ba5-d61895b15cac',
 'ecd9230d-c571-4dab-abd3-8b54c74833f0',
 '98219f72-0f9a-4de9-a859-c81834f24ab1',
 '0bae7ebf-eb54-46a6-be9a-3461cecefa4c',
 'd288b10a-643e-44bd-b451-96e9588b2ee5',
 '529bb209-9d7b-44da-bfa4-f6e4745c46c2',
 'a4157949-6f2a-40e2-b960-63f6e2bde918',
 '31f04740-c712-4c4b-a3f8-55c0506b3034',
 'd02287f3-408b-438d-9131-999e460cbd0e',
 '0920bcb8-4b3a-4e9d-a353-56f529fd3b32',
 '46ff9dc2-3d87-4b36-91aa-ffa8aa13c52e',
 'd2514440-d747-4d8d-b2c7-b58ef8b71fbe',
 'b62f728b-a7eb-4889-8162-b3d457de93b9',
 'd8da613f-e681-4c69-b463-e94f5e66847f',
 '1e4214ce-7347-4ec7-97b3-fcf7c1938e8b',
 '59b69042-47c2-47fd-ad03-d21beb99818f',
 '949ec7fc-ac54-47c9-bb6f-ee9e67688cce',
 '6ed0bb6c-a9e3-4ba6-9436-7c8fd4e206f0',
 '9f499d32-400d-4c42-ac9a-fb1481844fee',
 '0087cde2-967d-4f7c-8e6e-40e4c9ad1891',
 '77c1c785-809f-4065-8c54-6a0170783256',
 '7b316f62-7fa0-4b95-bac9-e90866038a85',
 'd2b5efc1-14c6-4b5f-bd98-40f9084872d7',
 '421e5f54-5de7-425f-b399-34ead0651ce1',
 'a19b218b-1c0a-4618-b41f-7c216c623ec6',
 '2e9d2f32-4cfb-49b5-b990-cbf4c241214e',
 'b2dda353-0c96-42df-8dcd-1ea7429a6feb',
 'c2aad8fc-b63b-4f9b-9cfd-baf7bc9c1771',
 '0de831e0-a525-4ec5-b717-df56f2de2bf0',
 '518d9049-2a76-44f8-8abc-1e2b59ab5ba1',
 '27d91086-cfe3-4e33-9282-bd1246e5ce8e',
 '8c42cfd0-0b0a-46d5-910c-fc833d83c45e',
 'a77176ec-96c8-4448-a3e7-b56940bdfab6',
 '7db0c178-b0a4-442f-ba54-e9e1633a84bb',
 '471647b3-04fe-4c76-8372-3264feb950e8',
 'e3ed2ba4-edf5-40ac-8750-8a417ad1eefe',
 '2f05ab20-a092-4bab-9276-3e0eb24e3fee',
 'ab326369-b63c-48d8-8a7f-82ffa0df7002',
 'd41f45c1-1b7b-4573-a998-ac5c5acb1647',
 '203025fe-fa99-4d57-81da-458ed8f0c334',
 '5ce42b38-d867-487f-9b40-e8bb00b21d0b',
 'a20e2f2a-e171-450a-8ddc-8935c2977ad6',
 'ef1a4b05-540c-4f73-8ceb-49dfa800645d',
 'cee9b331-3ba0-4461-8bbd-867819d9fc0a',
 '527641f0-df64-4c80-957c-a65dccd477bc',
 '01b84709-139c-4485-98a9-6e14c58fbbf6',
 '0b4a15a7-4e9e-4555-9733-2423e5c66469',
 '8f3e7fcf-0b16-4a29-a5f1-a7a8b267d689',
 '965386e9-1e4f-466d-bf59-ebdca4b66b9b',
 '0a2d7e87-c3c0-4ed2-86df-ae18811fcc16',
 '171b03c9-516b-499c-a434-fa4f70191988',
 'd967b47c-a9e6-4337-b2f4-977f690cb67f',
 '90d4a63b-5c02-43eb-acde-c49345681601',
 '9a281de7-cee5-4e80-8584-1929f46f152f',
 '9fcb0b73-c734-40a5-be9c-ace7eea401c9',
 '94c41723-b2c4-4b59-a49a-64c9b851903e',
 'c2a461b1-0c15-4047-9fcb-1f966fe55100',
 '5e717147-0f75-4de1-8bd2-6fda01b8d75f',
 'dea1aa78-c0a2-413f-b375-f91cce49e4d0',
 'aecc2743-4ff2-4b55-ac8c-a1ff76fc4bb4',
 'd5a2d011-3765-4dad-ac36-3fff087589fe',
 '7f08cbcc-5790-4576-8478-10e9a999b316',
 '881e0e6b-a185-45f1-9b56-81606e91e7ff',
 '8ff0cef9-393e-43de-9722-a1e12c239727',
 'cf83c98a-3791-4537-bbde-a719f6d73c13',
 '99950e99-2758-41d2-b2c9-643edcdf6d82',
 'b07fb54c-d7ad-4995-8bb0-8f3d8611cabe',
 '829a3cd1-a466-49f1-b2e9-d3f6b7f392e2',
 '3c75a463-6a87-4132-83a8-c3002624394d',
 '96baf2e0-60c5-48cf-b1d1-cba657851507',
 '52ea546e-9229-40ef-b048-a2e694dd73e8',
 'a37f857c-779f-464e-9310-3db43a1811e7',
 'f6cc8a47-2dea-40aa-8608-d771c5ef8a07',
 '11ff73e8-d3e4-4445-9309-477a2c5be6f6',
 'f641d68a-e877-4bb8-afd7-b8fa3921d461',
 'a30db232-08a6-48f0-ab9f-ad6977b8a6b1',
 'aad97cb5-f375-45ef-ae9d-178e7f5d5180',
 'ddb22b3d-a75c-4dd1-9730-dff7fc8ca530',
 '9d5df009-eb76-43a3-b6cd-22017cc53700',
 'ec6ceff8-c8bc-488d-b6bf-30df2fa92169',
 'b57462e3-1df5-463a-a3fa-4d67b93ef087',
 '5bc42b88-bb76-4954-927b-8bb7369adc64',
 'bab7432a-5cfe-45ea-928c-422d03c45cdd',
 '9968be68-ab65-4a38-9e1a-c9b6abece194',
 '9fddb063-056d-4202-8b8a-4b0ee531d3ce',
 '8fbed309-d3d4-441b-b3ff-e2dcbcec2d35',
 '37b21763-7f0f-41ae-9001-60bad6e2841d',
 '99e317c0-1fab-4f73-b511-859e752fd1c3',
 'c893ddc3-f25b-45e2-8c9e-155918b4261c',
 '17e9d436-a264-4c94-a42d-48c8daf6fdd9',
 'b46237d1-19c6-4af2-9335-9854634bad16',
 '2ac76f1b-43ef-4271-8686-2f165570989f',
 'a82c43bb-a703-446d-aa24-049bf013121f',
 '92161459-9103-4379-ae34-73a38eee1d1d',
 'e6dad530-418b-47f9-af6e-472e56a7b314',
 '31285bcd-9a28-48ce-8cc0-543af80261d3',
 'edbfa04a-f1dd-496a-8237-df11d70621ca',
 '3dc61ca1-ce40-46b6-8337-f27260fd9a03',
 'fe4b89d5-461e-440c-a5a8-621b37b122c0',
 '31f657dc-1875-4c4b-a5ca-ce63b3ef3a82',
 'b6b5ea88-e092-46e4-b9c5-e93b52d5c195',
 '30cd5311-6c09-46c9-94f1-71fe4b91813c',
 '75011e96-ba37-4977-a539-fbf9f66a5e37',
 '4319097a-acae-4124-beed-d1173ffe1464',
 '58f43044-cd3c-42b8-bc0b-3498eb236359',
 'e7c5ba7e-4be0-4696-af50-a07d0dc7aac5',
 'e84f2780-51e8-4cfa-8aa0-13bbfef677c7',
 '9c1b5626-58df-4401-ae7b-f66d068c1551',
 'f0f0d7c4-3bec-428e-9539-c99d36548d96',
 'e2a00644-0a48-4815-ae87-d562045114f5',
 '59632ec0-6f10-48c6-af79-81024e84843e',
 '242c6e7f-9016-4048-af70-d631f5eea188',
 'c54c9659-1b6b-4d4a-96f0-7dc987410f2d',
 'c0fb0d06-225b-4611-b802-d2f34b438a29',
 '30c2a6fd-d547-460f-a5e7-44c62a2af7ad',
 'b7efc0ba-9136-4f3f-adb2-d07849e59a3d',
 '5829c7ba-697f-418e-8b98-d605b192dc48',
 '02792605-4760-4023-82ad-40fc4458a5db',
 '429d21fd-bb9a-4abf-922b-c15138524bdd',
 'd6dfdef1-406d-4efb-808c-3c5eddbfe0cb',
 '3bfd5174-5b49-4e58-b233-ed0f4edd0bec',
 '3f6ab2aa-6c63-4753-b652-3a9b9e7c8ee5',
 'bd65a70f-b274-4133-b9dd-0d1431b6af34',
 'b3c9904b-2ffd-4038-8620-ee1c5b072e9c',
 '0ae6f031-2f9c-4247-8b26-db320d6efd32',
 '251b1a7e-d050-4486-8d50-4c2619eb0f46',
 '1ab4ebbc-18d6-4838-89c2-cdc5b10accfb',
 '145dcf6a-2461-4fa3-a0af-7fc56db0bd33',
 '56a4bc14-9407-45fd-8786-f7f6fc87c9dd',
 'e6361237-ac4e-4c5d-ad8f-f16aca0c0a8f',
 '432f3af5-6a79-401f-b315-fb2df789f32c',
 '9ddea8d9-cc4c-420a-90f6-880996f808d4',
 'b61a921b-7fa3-4b42-b455-aaaf32447920',
 '19f1bec6-eeb7-4133-accc-992d745fef89',
 '85c60876-7f35-40c5-a256-7808d84c6ba5',
 '0bf30b02-db97-4560-b9cd-0fe3588892af',
 'b693123e-95e6-4331-8b50-f367489a767e',
 '574e9f9e-f8b4-41ef-bf19-89a9964fd9c7',
 '4023a2bc-6325-47db-bfdf-9639e91042c2',
 '535e9336-2d8d-43c3-944d-bcbebe20df8a',
 'e1f595f6-ba2c-495e-9bee-7056f116b1e4',
 'ca46ffe6-0a26-4d8d-82fa-81722daf1102',
 '3294d050-6eeb-4a00-b24c-71aacc9b777f',
 'e7bd68ab-df49-44df-9b1e-8486114aeeb5',
 'ea95cdd5-cf7e-4d5d-a0bd-032776d32ae5',
 '4ed927e9-c099-49af-b8ce-a2652d069333',
 'd9f3a82c-24bb-4277-b715-8ec92a33dd32',
 '2adb1f8a-a6b1-4909-8ee8-484814e2d4bf',
 '60a29d0b-1a37-4447-ac32-00d701580b47',
 '43aa19d2-c723-4822-979d-d2f0239835e0',
 '15d374d6-0dfd-4d8e-ade7-81f73dc921ee',
 'a199ca73-035d-44e2-9893-4c493151db21',
 '576f193c-75d0-4a11-bd25-8676587e6dc2',
 'f32c2c13-bb1a-4ffd-a457-60b64ecfa4cb',
 '76150f40-1989-4977-9e23-696e72d59d9e',
 '21722308-5091-4b63-9c07-4f116ab9a7b3',
 'e40c6272-af77-4a10-9385-62a398884f27',
 '1873a18a-66fd-4a4d-8277-a872c93f5b59',
 'e595c979-c2de-4dad-8c02-8334a8e56de6',
 'cb252df6-6e49-4553-abd1-495a00006fb1',
 '8f4f8502-9170-4ac2-9707-3b6985ebfe5f',
 '6c87755e-a671-41a8-9c7e-4e43b850a57b',
 '5af90777-6760-4003-9dba-8f945fec6fdf',
 '9d8e5dca-03a3-457d-b7fb-844c75735c83',
 '1a974af7-8b4b-4abb-8aba-23e2979d9518',
 '0436a180-cb44-47ba-8ffa-807b7a468469',
 '9f1a899f-05a0-44c5-8aa9-39df61ae4324',
 '84cfa5aa-a0d1-415e-ac47-eb66c9cf8170',
 '8058d760-09e6-4bdd-86a1-36917ffca3ef',
 '4a5b00e0-1ba3-4fd4-af89-d3512eb20720',
 '21d3e683-80a4-4d9b-bc89-ebb2df513dde',
 '019c7af2-c827-4454-9970-44d5e39ce068',
 '1a2e3350-28a8-4f49-b33c-5b67ceb001f6',
 '5a9cfb44-494a-4540-8db8-7143b1bb5a6f',
 '4e374783-0152-423e-bcb6-b87cc232f64d',
 'a19d1667-a7b5-4556-9e5f-f9bfa690c0f1',
 '43245158-5ae1-4e71-a9a6-67eef49c26bc',
 '3f32121d-126b-4e8d-9f69-d86502d2a1b1',
 '1c739a3e-c3f5-49d5-98e0-73975e751201',
 '1d89d081-f43d-401a-be76-bd6ef9259f4e',
 'd68a8b48-abf0-4bd5-8834-155d34ec448a',
 '3b8b5de4-3aa1-4ac6-8890-8d03c8219981',
 '093d3bfe-6f0f-4ac0-a7a1-829f94d0a49f',
 '29244e1d-02e6-4133-b411-516ef7474638',
 '64267fb5-7b70-4705-a13b-cc38966c22a8',
 '7b55fe5c-d5c8-48e0-a1a3-54c5b9074f3f',
 '3c361813-5d5e-4868-bfe5-e7591e7b5381',
 'ecce9688-66ea-4600-98f7-84aed7421c01',
 'ac2fea99-ce08-4fca-8d03-a19f37bf21a3',
 'ed880090-465d-4477-9d98-70838ca288e3',
 '0bc7235a-ae5a-479d-a487-510435377e55',
 '93091496-be48-4122-b945-9af9c22a7535',
 'be41a86a-b606-4b1c-8055-32f334898775',
 '3079e9b0-c6db-45c8-b998-a4555a73968e',
 '7bb64315-9e5a-41b9-9235-59acf9642a3e',
 'b617ee1b-f8c8-4de9-b82b-e803ab93550d',
 'ed5d841d-6346-47d4-ab2f-7119ad7e3a35',
 'cda2c8cd-be1c-42e5-b2cd-162caa1c4ce7',
 '7f7faf6b-f11d-4f07-bc1c-188a4472748d',
 '7c497c66-c2e2-4291-8b96-339e5e65f314',
 'f5b0810c-1664-4a62-ad06-be1d9964aa8b',
 '716a4acc-919e-4326-9672-ebe06ede84e6',
 'a5d5c529-8a1f-40b5-bda3-35208970070d',
 '18e2a8c5-33f7-455e-a58a-b2ba6921db27',
 '5ed90bc0-12f3-4354-b314-0ce0dbb96458',
 'aa369999-a034-4ad9-b459-8a93c86ea77b',
 'f1606894-59df-4794-a37f-baa7c6fb6de1',
 'cd2f23c1-aef1-48ae-8eb4-0bcf124e567d',
 'd4e69e01-3ba2-4d6b-a15d-e7048f78f22e',
 '1b9d8702-5af8-4142-85ed-020eb06ec4f6',
 '72955cdb-bd92-4135-aa52-21f33f9640db',
 '34229bdc-a895-4394-8820-574e4028d8c6',
 '7b20c613-9add-43d1-87e9-defd3d9b9f8c',
 '963a08cb-d995-4862-9614-f9d38a7d7540',

## New to do datasets

In [14]:
df = latest_census_datasets[latest_census_datasets["dataset_id"].isin(difference)]

In [15]:
print(df.columns.tolist())

['soma_joinid', 'citation', 'collection_id', 'collection_name', 'collection_doi', 'collection_doi_label', 'dataset_id', 'dataset_version_id', 'dataset_title', 'dataset_h5ad_path', 'dataset_total_cell_count']

In [17]:
df = df[["dataset_id", "dataset_total_cell_count", "collection_name", "dataset_title", "collection_doi_label", "collection_doi"]].sort_values(by="dataset_total_cell_count", ascending=True)
df

,dataset_id,dataset_total_cell_count,collection_name,dataset_title,collection_doi_label,collection_doi
288,149b2c3f-ee11-47a7-984b-923570280bd7,301,HVS: Human variation study,SstChodl - neocortex: Human variation study (HVS),Johansen et al. (2023) Science,10.1126/science.adf2359
441,5e7fff82-b8eb-4220-bf65-c6feb6765ea1,563,HVS: Human variation study,L5ET - neocortex: Human variation study (HVS),Johansen et al. (2023) Science,10.1126/science.adf2359
398,4859642c-d155-437b-adf5-83ca6c1bef67,582,HVS: Human variation study,Endo - neocortex: Human variation study (HVS),Johansen et al. (2023) Science,10.1126/science.adf2359
417,f9cfac8d-bff6-47a2-a1f6-503827d375f5,637,HVS: Human variation study,VLMC - neocortex: Human variation study (HVS),Johansen et al. (2023) Science,10.1126/science.adf2359
193,61d327d1-2227-4c5f-9367-e3559dc79b07,796,Characterizing smoking-induced transcriptional...,Characterizing smoking-induced transcriptional...,Duclos et al. (2019) Sci. Adv.,10.1126/sciadv.aaw3413
...,...,...,...,...,...,...
1802,aa32098f-f7b0-43f2-a00a-601d190aae94,2596111,Multi-omic profiling reveals age-related immun...,"Sound Life Older Adult Females, CMV-positive",Gong et al. (2025) Nature,10.1038/s41586-025-09686-5
1804,46104f0b-9af5-466a-ae0f-56b8dc1969a2,2616824,Multi-omic profiling reveals age-related immun...,"Sound Life Young Adult Females, CMV-negative",Gong et al. (2025) Nature,10.1038/s41586-025-09686-5
1846,d6505c89-c43d-4c28-8c4f-7351a5fd5528,3177310,Single cell atlas of the human retina,snRNA-seq of human retina - all cells,Li et al. (2023) bioRxiv,10.1101/2023.11.07.566105
1833,f7c1c579-2dc0-47e2-ba19-8165c5a0e353,4062980,A human cell atlas of fetal gene expression,Survey of human embryonic development,Cao et al. (2020) Science,10.1126/science.aba7721
1845,37a17b78-4864-4a42-b67b-31c00962795a,4140453,Population-scale cross-disorder atlas of the h...,MSSM_Cohort,Lee et al. (2024) medRxiv,10.1101/2024.10.31.24316513

In [18]:
mode_values = np.where(
    df["dataset_total_cell_count"] < 500_000,
    "cellxgene",
    "cellxgene_advanced"
)
df.insert(2, "mode", mode_values)
df

,dataset_id,dataset_total_cell_count,mode,collection_name,dataset_title,collection_doi_label,collection_doi
288,149b2c3f-ee11-47a7-984b-923570280bd7,301,cellxgene,HVS: Human variation study,SstChodl - neocortex: Human variation study (HVS),Johansen et al. (2023) Science,10.1126/science.adf2359
441,5e7fff82-b8eb-4220-bf65-c6feb6765ea1,563,cellxgene,HVS: Human variation study,L5ET - neocortex: Human variation study (HVS),Johansen et al. (2023) Science,10.1126/science.adf2359
398,4859642c-d155-437b-adf5-83ca6c1bef67,582,cellxgene,HVS: Human variation study,Endo - neocortex: Human variation study (HVS),Johansen et al. (2023) Science,10.1126/science.adf2359
417,f9cfac8d-bff6-47a2-a1f6-503827d375f5,637,cellxgene,HVS: Human variation study,VLMC - neocortex: Human variation study (HVS),Johansen et al. (2023) Science,10.1126/science.adf2359
193,61d327d1-2227-4c5f-9367-e3559dc79b07,796,cellxgene,Characterizing smoking-induced transcriptional...,Characterizing smoking-induced transcriptional...,Duclos et al. (2019) Sci. Adv.,10.1126/sciadv.aaw3413
...,...,...,...,...,...,...,...
1802,aa32098f-f7b0-43f2-a00a-601d190aae94,2596111,cellxgene_advanced,Multi-omic profiling reveals age-related immun...,"Sound Life Older Adult Females, CMV-positive",Gong et al. (2025) Nature,10.1038/s41586-025-09686-5
1804,46104f0b-9af5-466a-ae0f-56b8dc1969a2,2616824,cellxgene_advanced,Multi-omic profiling reveals age-related immun...,"Sound Life Young Adult Females, CMV-negative",Gong et al. (2025) Nature,10.1038/s41586-025-09686-5
1846,d6505c89-c43d-4c28-8c4f-7351a5fd5528,3177310,cellxgene_advanced,Single cell atlas of the human retina,snRNA-seq of human retina - all cells,Li et al. (2023) bioRxiv,10.1101/2023.11.07.566105
1833,f7c1c579-2dc0-47e2-ba19-8165c5a0e353,4062980,cellxgene_advanced,A human cell atlas of fetal gene expression,Survey of human embryonic development,Cao et al. (2020) Science,10.1126/science.aba7721
1845,37a17b78-4864-4a42-b67b-31c00962795a,4140453,cellxgene_advanced,Population-scale cross-disorder atlas of the h...,MSSM_Cohort,Lee et al. (2024) medRxiv,10.1101/2024.10.31.24316513

In [19]:
# number of new cells
sum(df["dataset_total_cell_count"])

107602752

In [20]:
import datetime
today = datetime.date.today()
print(today)

2025-12-03

In [22]:
output = f"datasetIDs_human_has_primary_data_new_{today}_{embedding}.txt"
with open(output, "w") as f:
    if embedding == "UCE":
        f.write("# List of datasets: new (latest - Census2023-12-15 - NRP), human, has primary_data\n")
    elif embedding =="scimilarity":
        f.write("# List of datasets: new (latest - NRP), human, has primary_data\n")

    df[["dataset_id", "dataset_total_cell_count", "mode",  "collection_name", "dataset_title", "collection_doi_label","collection_doi"]].to_csv( f, sep="\t", index=False)

## obsolete datasets

In [23]:
obsolete_datasets = [x for x in current_datasets  if x not in latest_datasets_has_primary_data]
obsolete_datasets

['8e10f1c4-8e98-41e5-b65f-8cd89a887122',
 'b165f033-9dec-468a-9248-802fc6902a74']